#!/usr/local/bin/python3

### Tip: Make sure you enable "Pause on exceptions" and "Pause on caught exceptions" in Chrome Dev Tools
### Tip: Use regex101 to test your regular expressions

import re

folder="www"

with open(folder + "/logic.js", "r") as logic:
    lines = logic.read()

# Deobfuscation #2.1: Simplify

# - Booleans
re_true = re.compile('!!\[\]')
lines = re_true.sub(" true", lines)

re_true = re.compile('!\[\]')
lines = re_true.sub(" false", lines)

# - Array-style function calls
def transform_arraystyle_fn_calls(lines):
    re_arrayfns_sq = re.compile('\[\'(\w+)\'\]', re.IGNORECASE)
    def sub_arrayfns(m):
        return '.' + m.group(1)
    return re_arrayfns_sq.sub(sub_arrayfns, lines)

lines = transform_arraystyle_fn_calls(lines)

# - Convert hex numbers to decimal
re_hex_numbers = re.compile('(\[|\(|[-+*/:&= ,])(0x[a-f0-9]+)', re.IGNORECASE)
def sub_hex_numbers(m):
    return m.group(1) + str(int(m.group(2), 0))
lines = re_hex_numbers.sub(sub_hex_numbers, lines)

# - Because our hexadecimal identifiers have different lengths, we are likely to consume 
#   part of the wrong hex variable/literal/function names.  We will avoid this
#   by post-fixing them with underscore.  They are already prefix with underscore as well.
re_hex_variables = re.compile('_0x([a-f0-9]+)', re.IGNORECASE)
def sub_hex_variables(m):
    return '_' + m.group(1) + '_'
lines = re_hex_variables.sub(sub_hex_variables, lines)

with open(folder + "/logic.clean.01.js", "w") as f:
    f.write(lines)

# Deobfuscation #2.2: Undo shuffling

# - Introduce a debugger statement to manually capture the unshuffled strings array
lines = lines.replace("_568a_", "fn_getStrings") \
             .replace("_4573_", "fn_decode") \
             .replace("_18d5a8_", "arg_fn_getStrings")

lines = lines.replace("break;", "debugger;", 1)

# - Replace the only invocation of fn_getStrings with the resulting string array
lines = lines.replace("var _568a0e_ = fn_getStrings()", 'var _568a0e_ = ["WReOeSo1","gupcNmkUW4qpW7a","W47dS8oQiSkpE8kTaG","EmkQWQBcLaasWQVcRSo5","W5NdVSoliG","W4jRiCkrW6a","WRzWq8kX","W4ddImoQiSks","rfasESkXWOG","WPqMWO5n","W6JdHYpcSHldReJcO3VcRH7dTCoX","ChGWvCkXWPtcIItcJ8k1qCoXW67dMq","W68KjflcI8oOW4xcJL0","WRfXr8k9W5RcOmkx","tcpcQCkEW4lcQ8oP","FSk+W4WH","W4xcMqRdG8kAWOFcJ8og","C8oKWPm","W4xdLchdLwNdHSo0WPe","WPBdN1VcMCogW77dMSkyWP5MW5e","arxcPItcKa","WQxdMLK","yNHqW5y","AZz3","jKPHqG","x8kWdrLF","rCk4E8oDW6BcJSotW7ZcPa","WQFcJCocCs8","buVcM8kLW5G","oKxcOCk+W5KrW60f","zxFcThWBwCkEWP7dVSoNjdpdHYW","WQy1W6dcOW","lXJdG8oW","DCotWPtcMSoN","W5qCa8oqiW","bCoiDCkMW5PgW4RdTCk+","W7ZcRb3cMc08W5FdQSkKAmoa","d1ddTM7dLq","smoBW5RcQGJcVt9jW4BcJ2lcU8kXWOKmACobtCoRW4jfzG","WR/dO8kaDYW","leHVvq","WRRdTSkazh7dOKS","WQddVf3dGNO1W6NdN8kA","W7ZcRrlcMYrHWQ/cGmkSBCoMA8k2WOq","W4BdHComW6lcVhaJfCokghOQm8o9cwdcG2yMWQO","CcWyW5zOW4S","W4tdMZBdTN7dQSoN","W4fezCkEnmoXrmoC","xbaeW5PQW40orbtdR8ky","hqxcTZhcGaW","WOzVW5mEW7y","WRyYeCoIW5xdRX0NWQpdPvu","cwPtja","WRdcHtdcJqNcIfjW","WO3cPuGbWQq","zSkHWQdcLqO0WRS","bWJcOthcNs3dSq","W74yia","WP3cVLKwWR4SwYzBWPrr","eWWoWORdM8kOl8okhXab","WR8UW7FcRHtcKSkL","W6ddLde","BYOeW5r5W40","WRzQtCkSW4hcOmkCW6C","aLTjW53dLW","AY4zW7X6W4SQwXRdRCkyW49HWOu","WRpcMSoFDcdcN8o7","heFdTeuxzCkGWR4","WO3dNCkdCsBcQrBcG8kuFSoYW4uLy8oqWQ8DWOvzW6ddOa","FSkZW4mHjGBdSY8YWP5q","WPPsWPy6la","w8k1BmoaW6FcGmovW74","WQ56WReAorigl8odkq/cJ8onxG","udNdMqiNWP7cPu8o","W54igJmqbHhdUuaG","W5XfuSkppSoxta","WPDhWO0+jauxcCopnXtdHCogb1naWRL3CG","WRpcTmoglG","lfzQvmovymov","DCoqWPpcMG","WQ3cMSobFZxcLa","fCkMW4tcSW","gCoXWOJdQH8","WRpcUSoalG","w8orW6lcGbpcVsbVW4NcIhq","xSoVq8klga","wuazB8k8","y1qvCSk2","WPpdHLNcHCohW5pdKCkf","WQ/cQre","WOaThSoVW5BdKaTUWPtdPu5gW4e","nCo+WPJdUXGDW7m","WQJcJW3cNG/cIq","je5VwmobEmoAWOvTqW","D23dRmkBW7fcg8oL","wSoGxvzD","WPBcMqa","rKdcMt5WW59TWOZdJWW","WQxdMLNcNa","hJavFW","W782ahnboHNcRWzqkmk0W6ZdMq","FCoGtq","W4NcSbNdQmo4","CtztbsFcQSkLoW","evJdV18uzq","wSoMw1zD","W7JcGhxdUG4","tSklWPRdLqe","rh7dTmob","DCoxWPK","vWddHga","WPpdLSk9nbdcQaFcGSkmDmoSW7u3zmocWQ4","WP5ZW7y","WOhdRu7dMxW","fWyVWPpdGmkYmSoe","AmkBtG","wZNcVW","FSk7W44","WRDZWQtdSqK","dGGF","yJX0mchcT8k5nstdVrRcSW","btaeBmorACkkWPCh","q8kHWQ/dNuJdTrSJW4JcNW","cGCyWOldISkuoG","mMeRW5K","W4jTla","W4ZcH2hcQtC","WQ5IW6q","WQySW6BcRaxcS8kW","cCkvjmoUW5a","WP3dObC","zCkGWQ3cNG","WQG2WQBcSa","WPBcKqldIG","DCosWPtcMSoN","W7JcRSkmWR3cTq","WPXXW5SsW7OwDW","W5FdR8o2jmkuD8kTeCkuE8kSWOhcJG","v8k0aqTnqXnctq","sqrmjW","zgG2sW","s8k5WQRdKvZdRrq","WRxcHSoFFq","WQ3cHaFcNapcRLO","WPChW4C","WQddJSkCiG","qSoFW40","W5VdTuFcUW","zYajW4zGW4auxq","WQpcJXFcQqNcJKH4oCoEBCoLW6H6","W4NdKctdUMxdGmoyWQzpuG","weCtBCklWOhcLXm","WOfEWPm2iHefxCowmbxcHmoB","kbFdG8oSW40iWR4","WQn6qSk9W5BcOq","WODcWPGGnduteCodoW7cHCom","ebKqWO7dHG","bSo1WOZdPryxW7i","WP7dH17cLCosW7NdMq","W4S6D8opW6NcUIWS","gmoXWPldRGivW7dcSmkv","WR3dVLNdJNG6","W6jcwmkokCoVwq","w8kqW4VdHCoW","AJ8cW5XJW4a","WRqSaSoKW5tdGLuRWRZdUurgW5CmW4JcQc9LW6m","W6q0avLtoG","WQP/kgincwpdTa","W5aQDmoyW7hcRq","cCkrla","sSk3ACogW67cHSod","AshdTG","hHhcQaVcLGhdUaRdKG","W7GNfLi","W5q/avnBmq","hCopCSkXW5nCW4VdTSkU","yCk/WRZdM0NdHW","W4fCECouwCkiWP7cJa","W5RdMJtcRWBdMG","WRD0WQtdSq","WPlcNSojEtpcLq","CCkZhWbn","umkqWQlcIbyjWRtcVCoUWQ4WBCk+W4tdHCkjW5T7WQ0","W5JdK8oRnCktvea","W4VcTrddS8o1","WRpcTCohlIe","WQbTtmkRW4dcQSkhW5OiW6q","W5BdTCoxi8kf","ztOeW5b5W4Wvr1xdRmkiW5HNWOueWOVdM8o+WQKna2GtW5FcTaizswbFmmo/W63dHq","W5yNa1bt","WOfsWP82pW8agmou","WOnzWPK3kW8ygmoc","W5VcQCkiBa","tfakDmkMWOxcQH/cKSkHwmogW7ZdMCkwfa","BSo5W74","odvdW4hdRW","sSoiW5rzfqFdOc44WOu","yYtcV8kEW5ZcI8o3","WQNdUf8","WP5UW77dRGfnw8kqWOhcKCoWb8kk","EHldGmo6WPnmWRCSlSoeW7LQea","WR5UW7tdVGy","DSo7WPv/","amo/WQ/dVquDW7NcSG","DCovWPlcMG","W7hdQmoAW6e","rhNdV8ob","W67dUCokiSoDv8kXf8kAFq","W7BcRr/cNY1GWQ3dHSkjECoEACku","rgdcIL0NWPBcP1Kp","WPqQWOLnW6q4FCkFsa","t1aiwmkPWOxcLXpcHmkWDSoTW5tdIq","hcfWWOyy","W5DcCCoqra","zg05sW","yt3cVSofW7DzgmoLW5G","Cmo+WOb+fsddGXar","DWG4bmokqmozWRDqxq","cZGlCSoTF8kjWPqDw0Dr","hCo+WPJdRa87W7e","EulcKYHK","wCoFW4lcMGe","W57dK8o7p8kEEe7dHComBCo4pG","WP3dPH1j","WQvXr8kQW5pcOmkDW6Wz","WQj6u8kJW5tcQSkw","W5dcI8k8ASoA","qIJcUCk6W47cKmo9D8kjbwHC","WQddH8kziIq","g0NdUuyBCW","W7q2n0NcRCoUW5tcJ1S","zMlcP0y","WRO3pCoQW4hdSXC7WQFdPxfhW40lW5pcTq","gYKlD8ok","W4NdV8olm8kyFa","cw9FjmoB","W7CKpK7cIq","WPCeW4C","W7zMrqy","WQbCWP81W7a2zSkFshq","WRZdO8kcFspcRbdcHCkq","WQxdKLK","f13dO1uismkAWOCi","D2NdQCkB","FhNcGeCdsCkpWRxdJ8o7ka","DCoqWPpcMSoN","eG7dGW","aZuZF8oCu8kb","WQiQfmoUW5/dJHyRWQa","zgG3sZa","xfOVACk3WONcLbe","W7ZdNmoS","WPSbW4VcNYtcKSkn","tSoDW4hcNa","WQ/cRH3cKwG6W7NdLCkoACofqmkHWRe","w8kRySoaW67cM8oEW6pcSW","nt3cJcFcTWFdOrddJCo8W4HDAa","rh3dTW","WPCpW4vOka","W4JcPqxdRCoTW6fY","WQtdIfFcG8oFW5JdMmkZWOTHW5jCWP7dMq","BY4eW5r4W4qDtay","BmowW5ZcGaNcVq","DH/cQmkkW4/cGCo8AG","WRiVW77cIHNcQCkSW7/cVcxdIxVdHq","WQyHW6hcUaK","W7xdS8orW7lcQa","zgW4sZa","W5BdMmo7","rmoRqG","W5qCaSoqiW","W6/dQmoFBG","W61CACoCqSkfWONcL8oqWQBcOCoMyH7cJSoeW78","D2ZdPG","WOFdM1xcHmofW4ldHSkbWPW","zhpcP0av","WQ/cRX/cKq","Emk4A8ovW7pcHG","zJdcVCopW7fFaW","yN9q","WRxdP8kautZcUqhcHmkrCSoVW7q","r8oBW4FcIaZcRa","bGFcTHVcKGZdHW3dICoPW4LYqxe","WQddJCkxiG","uCoVsKHhWPRdHa","t8oKWP11eW3dPrGRWPjAW7G","WRz2r8kXW5W","DCoDWPpcMG","WRLXr8kQW43cHSkv","wSoIwvzD","md1QWOWhyCkoWQ7dVMSEiXldPSkNW7lcVY11","wfpcGdnIW51TWRddIa","WPBcMGVdISop","W7ddLCoS","WR3dRuFdGMK","tSkpWP3dLq","amo5WPhdRc0BW7NcSa","zgOZsZa","W5SpbJmAkXRdRfa","WRrWqmk6W5JcRmkDW70","wSoVWPnA","fCkHW4NcSW","WPtcSCoIwrlcT8oBBsZcMM1/bmoEgh3cUSoUefTfeCk9","dCk/FCkj","cCktla","W47dMYJcPatdIf4","At7dKXi5","tSkjWPRdLq","WPDbWPW7is4tfmobma4","utJdRHmZWP7cPu0","WR8LaSoVW47dHGORWOFdOK9lW5exW5xcO3SPWRu","lXVdGSoW","W7JcG37dUG","WPqUWO9nW6C","EHlcVSkpW5xcLmooCSkhjhvuW4JcO1q","WOxdLdZdQIVdLCoUWOTXB0CqlN5NWOG8WRCtWRu","w8oVtmkdaSksWQ0yqbK","BhNcR10zsCktWOldQ8oKkdddLJe0","q8oKW7tdKq","W4jhC8oArmkcWOpcJCoqWPFcTSofEGpcLCopW6PrbaVdSmkJWPddOSkfWRNcQKK7W6RdIvHGWOxcVSkLW4C","x8o1rL9A","WOVdUuZdJG","cw5sja","ja44c8oi","WRpcSmohlNq","d1pdVW","WRLdWPu3pW","nKHIwmoz","WPVdJftcL8oEW54","WRz1q8kX","DsXZgq","WQhdSSkyFta","Fd1SWO4gk8oxWQtdTJetoqZdOW","W7JcIN/dUG","W7aYb3LAmstcUaDud8k/W5hdHa","WR5UW74","zsJcUCot","WRRdSNJdN289W7pdLW","AwBcVeqn","yJ0h","jKVcGCkfW5WwW5mqfmo3W6zzi8kc","evNcL8kMW44wW6OxfG","W4RdKcBdLMRdGmoSWODXB1eGBuLPWO4aWQuBW7K","WOdcKColAI7cLCo6","WRRdSMFdHgOXW6/dS8kjC8oo","j8oXWPRdQauD","w0uqDmkX","mJDR","kf/cNmkPW58rW6Wm","oZbXWOqcCa","EsRcTCoeW6Ted8o0W4mImG","BSo7W7ZdIG","W50uacuima","WRFcQsZcQW","W7JcRSkkWR0","DYJcRmonW6Xtd8o0W4mImSoMuebCgmoOW7i","aGNcPJxcKqVdUbe","pHqqF8omFW","W5VdQSoyp8krwSkMdmksz8kX","WONcO0GbWPWLvZTn","WPOLeW","WRpcS8oalG","vWhdHMbJW511WQZdNW","wSoPu8kjeCkz","d1hdTg7cGa","yNXtWOK","W5qAbSoq","W4yaediliWBdRhCNDw/dLatdQ8o7W7JcHXm","yNXtWOLO","atCdE8ogvCkd","pdT0WOWlya","WQz+t8k6W5a","cCkziCoUW4bBW4hdTSkSeSkOaM4","W4aafd8BiWddPKy","WQHPW7tdUaftta","d1BcVHT1W7fq","WPddJe7cTCogW5pdKSkuWPD6W6DwWRldJW","smk/gmow","W6OafJmOkXNdRhiNAwhdGai","W4jNjCkr","W5FdPa/cHcldVG3cJhhcVXRdTCoXfCoheX45","DCoCWPtcMSopWONdVq","WRD2WQhdSqK","zxjBWPv+W4WEfa","W4LtAmoq","smkHdG9t","adWoECowBG","EHlcUSkEW5JcGmo9D8kDfw5MW57cSLujvNTlW6lcKa","WRpcS8odlG","r8oRv8kfe8kwWPadvW","ymk6WRdcLqaZWONcHSoh","dbpcRdJcGsVdKW","r2lcPe0g","rfpcMd5QW5e","WPxcVKKwWQunva","vGWOW4fIW5ijtaC","D8oUWP18dXW","WPBcMG/dISop","WP3dPX9j","WO9UW6ldRWHvua","dqFcPJZcGd0","pvRcNSkJW58","WPCeW4POoaGsgmoamrtcJ8oA","W5OomsiokXRdRG","W7O1WQtcVv0ogCo6WQxcJ8ozh8k8","ydNcSmouW6a","W47cRYBdTCo+W6T5WQa","yN1BWOK","Dcye","cwTujmkp","E3/cQa","wSoGx1zEqXHuwW","jaG0","AsxdTbir","hapcTtJcHahdSG","WPNdIfFcLq","zIxcV8kuW5FcGq","rCoJt8kzda","W5VcQCknBa","WR4QfmoUW4hdQb4","oIFdUHTermk3WQZdOSoGjG","pcz7WPmF","tdNdMqi5WRJcRq","WQJcSmo8","W5qzd8oqiW","y8kbW4hdHmoWWOhdQmkhWQy","sCosW4hcGby","vJ3cOCksW44","WOddGfq","WRHYW7xdUbC","W4zBwSkdmG","W4xdKSoCp8kEAuxdKW","WRTIW6ddPG9ztq","WPLWW5WwW7yWFSkc","W7e3pu/cG8o9W4JcKuO","uCkMkrX7ua1xsSkcW5PYuG","WP9zWPK3nsKq","q8oVW7FcJG","WQVcIaK","lXVdHSoW","wLamCCkKWOpcNW","q8oGW7BcJG","WP3dPHC","rJJdKXmKWPNcV24fWO5+WOO/Dei","WR40h8oV","W77dLZlcKaRdJuZcONVcUq/dQa","W7i1pLlcMa","sSk4WR3dGeRdGX8I","W5joqSkLmCo2ESojFmoeW43cKmkDWQlcLY8HW7FcR1FcKmk8gre","W6xdG8oom8kFDSkXdmkdASk3WRhcHr95BqH3cmkx","WRFcNGlcMHa","W5zxBSowxmkDWONcH8k/WPpcRCo/yr/cJW","cwXrjmokAmkqWPq","W53dLmoHjCkt","W5CWrCoFW7FcTJe4","WQxdNvK","vWBdGga","WRDXWQRdSqK","CCk2gqbCWOhdLve","WQrWB8kGW4lcRmkbW4OCW7xdRa","W5JdNclcSGtdLKK","W4ZcH2FcQq","oJT8WOyss8of","W7S2hvTdns7cUbO","WPqPWOXnWRm","W57dGdddOhldLW","zgOYsW","mMqQW5K","W6qRmuNcLCo5W4u","rCopy3T7WRJdPxdcOhS9W7ldIKumWQyfWOpcLJNdOa","W4ieddeikG","vSkrW4xdHSoNWPO","W6VdV8opW6VcSxyO","hrBcQt3cKq","hdy0ASomC8klWPy","WOrsWO0+laut","z8krW4hdK8o2WPO","WRpcS8oblIe","W5/dKcldV2FdHSoK","WRlcKmocFq","WPvfWPGZoqmZeCodnr/cHmok","d1xdT27cGa","W5VcPCkd","ctSum8okDCkvW5Wvqfnrwa","WRz3rSkXW5W","WOtdIKJcLCopW5G","C8oKWPD6eWhdUdm","yN5CWOK","Fmk/WQJcMqy","WOz8W40sW6C3","W78JhLa","W4HxC8oErmkd","kqNcQJpcIqFcTZBdImo6","ivNcKCk6W54","vZBdKWmUWPO","W53dMmoHn8kFCW","WQhdTSkvDY8","WPNdIeZcMConW5FdI8kEWOS","W7JcQ8kpWR0","sq1jj8kG","WQPOW7/dOqDF","vWldJa","aZGuBSoBAmkwWPOkxLnEyGtdK8kbW6D6bSkfW5Hzhq","W6xcSb3dOmoIW7z4WQO","CCkZgaa","q8oLW7FcJG","itr2WOCfAq","W43dQmowW6pcTxS5","WRxcKmo8BdpcLCoWtG","hJr7","WRpcSSoo","ASkPFCoyW6q","jZPlWPCyBConWQW","vmkGgWLkAIbQCG","W7pdSSonoG","euBdS1uct8kO","sZBdIW4MWPBcV0mfWOm","lXZdH8oWW44","DCosWPdcMSkY","BSo8W7ZdIG","WPnpWO0","W57dRSoom8kFtCkHeCkB","wmkkWOBcTZ4KWRNcRSoPWQKiv8k6W4ddH8kyW599WQ0vuwTaWQ/cIq","vWBdJ2bG","W4VdMt3dVhq","W4i9zCkgW7hcSc9YW6tdQxfUlq","W7e+bIqvnbhdU2STBw3dJqpdUmoQW7m","WPpcGW3cNrtcLK8","W5JdMZBdTMddJmoVWOD7","wLpcMd1WW51+WRO","F8kUWRBcGXC","oM/cOg8evCkZ","rCk2ECoDW6FcHSoeW7lcOSkIWO3cI3a","W6pcTSocjhldVLFcHCkvqSoXW5G0","WQxdM1ddGX4","WOxcHCk9ymotlXldUmoTt8oWc8kG","WRn2W40sW6q2Aq","WOvuWO83kaG","xmoDW5ZcIGhcTG","sItdNHC0","W4jUl8kr","hmoowSk7W4jqW5FdKmkRcmkJ","WRZdIfpcN8oz","W6ZdQCoAW7xcKxiOeSol","CtzmhIlcPSk5hYFdUWS","CCkWhabn","pJr7","BSo/W74","CCk4fa","W4ldMmo7gCkFFKS","zMm1wCkmWQhdMJxcHCk2rmo7W6/dJmkleSkDWOG","rhVdVSobWOS","vCoLsv8","BCoUWOr3bGVdSG","WRxdP8kardBcOHdcHCkwySoWW78FAW","W4ldJCoJoCkF","sSkGcH5b","rSoqW4RcIHZcLZq","WRPYW7ldUrPiqCoEWRy","zcOEW6DKW4GFuXRdS8kyW7jZWPPFW4FcJW","uCkNWQldNva","lXJdGCoWWPO","WRPEWPmNnq","WQxdNLFdGX4","hKFdPxuBy8kM","wmknW43dLCo6","WQFdS0/dJMuBW7S","WPzTtmkIWPxcQSkCW6ywW6/dRmkYjmoE","ESkfW5xdICoLWONdQSknWQy","WQrTvSkQ","xLpcHrvYW5jjWQ3dLr7cOu9aWRG","W5VcRCklBa","W4OoasmrjXRdVxeKFMhdHbJdRq","bfzQq8ocrSoxW4fBwCkhymo1W53dKa","xSolW4VcNr0","WRmHhSoIW5ZdGW","WQpdT8krzJ0","W7zKqGy","EmkbW43dH8o2WOa","W4hdLCoUpSkFDeVdNmol","DCorWPdcMG","vCkkW4FdKSoTWOhdUSocWPBcMMlcOc09AG","DHRdHSo+WPTmWRmugSo+W7zNbG","W6b2zqe","rgBcHv0","wSoJx1y","WRXXW4SsW7a3DmkydupcIvydWRxdR3pdVa","sqDg","iaeoWOJdN8k+","tSknWPq","qJldIsiTWPlcPK8eWPLjWP4tFG","zgO6","q8k4FSo7W7BcGCo3W6hcUCk7WOFcL3D5","vZldJqSGWPtcRG","WQP/kgiqDXtdT0a","W4pdKSo6pSkp","kCk7W4eVv1RcPZuVWOvBW7ZcRa","E8kGWPFcHaasWRpcRa","vWFdG2bG","WPWLgCoKW4O","uSkYWRZdMu3dKqeUW5pcMq","C8kbW5FdPCoUWO3dS8khWRRcNh7cLsCmECoYjmkulKC","rgxcJ10","grJcRq","yxJcQe0my8kB","j8owWPFcL8kXW5ZcR8kOWQdcNKVcOq0","W5bDtSonqSkcWOlcHa","grdcOaOTACkGWQ4RWR1v","W6VdLZBcRaRdNeG","CmkcwCovW7pcImocW6FcI8kw","s8oAzLTgWPFdJfhcJxaL","W6Gkaq","xadcMZ8QW5fWWRVdIG","WRPIW7ZdRWbtxCoD","wGzZfdNcPSkLntpdPthcS8oupcPGWPtcSe4","W6u2zmooW6pcScC","rfFcHJzKW598","FSk+W44","W5VcRSkmBa","sZJdIG","WReUemo1","rg/cIL0cWP/cUuuhWOGRWQGj","W65WFSklkmo8rSoEyCoPW7u","W5BdGIpcSGO","fCkIW4BdRa","W4OXCSooW73cKdK","faWEWOpdGmkYkSogaG","rhtdVCob","W4hdNmo9i8ko","gmo1WPldRGmC","BSoqW4RcNqVcSty","WOlcGXhcNb3cJKq","pcDXWOqdAG","WQxdNfBdGW","WQmUW7FcRGRcTmkTW7FcUq","WPBcNqdcLq","aaysWPtdHSk6mSoxua0gW5aEW5Lq","luX6qCoEfCkCW44","W53dKcddVM/dLSoYWOTWDve","FCkkW4FdHCo6WQFdUa","wLayDmk3WOxcMqlcQCkRqCo6W6K","W77dV8olW4JcP3SDdSoqbuaTkCoZp2tcGhuXWQFcR1xcQ8oi","WPv7rmkQ","W5ldLCo9p8kgFGBdMCol","BSo8W7tdIHC","W4ZdRSozWR8","W6CpfJmq","yv7cNCkLW4CAW6iqvmo3W69knmkEW6mxW4ZdIvJcRCkQWQPRWQHK","yCkxW4BdKSodWO/dU8kmWQa","rhZdU8ob","W7zNsq","nsb2WOaEBComWQu","sYZcUCksW4ZcGCoSCCkpfq","mMqUW5Kp","td3cRmkF","lX/dIa","cGpcSZ3cHGFdJZVdTSoq","W4CpbJmedri","wmkPyCoDW7u","WP3dPr5jWRG","WQddP8keEcxcRGe","xfOWCSkYWOxcIdxcI8k3uq","W7JcG3W","WQZcIXhcNqZcGe5YdSoiC8oJW5jUW7ZcLSo+WOTw","W4uhkSkdvq","WRz2rmkXW5W","w8kuW4BdKSoJ","W4RcSHRdRmo8W7y","aLHfW50","tSkpWPRdLq","kvLGvSoytSouWOq","WPqUWO9n","W4zBrmkpj8o8xSojzSoz","vIJcVSkiW5pcI8oHv8kp","v8kWaqTmsG","wSoKxfy","WQu0W7lcVWK","WPBcMWldISop","WQJcKColFtNcS8o4","yNDCWOK","WQ3cMGZcNq","zmkUWQ3cNWe","aCopCSkXW416W4m","D8kfW4/dJmosWOddV8kmWQdcH2a","W67dS8oBW7pcUa","WPO7xSoQW7xcKHy","WRtcJXhcLblcKK9+iSojBG","iSkXga9pWPZdIMlcTLS","rKdcMsPlW510WRO","WQrMW7pdOWbotCoC","dSotE8k9W5S","ftXQWOymA8oB","BmoOWOz+aGy","WQxdMvxdGW7cJ1HYk8ooC8oLW4nF","ELVcMc99","WQn6tCkRW7FcRmksW6OsW6G","d1hdVg4","z8oOqa","krW0","fxhcU8k5W7KDW7unemoIW6D2cG","d1tdSM4","rhtdVmobW58","WPzWW7KfW6m0DmkOrha","Bmk2ySotW63cISkhW5RcUmkO","W57dN8oL","xfBdVgtdNfFcPu/dOSo0W6forMK","cWGoWOpdHCk6lSogmXeCW4ecW4vfvHbPva","mtNcTtZcHaZdOXddI8o4W58","WRpcS8oflG","eayrWOi","WQNcHqFcNa","WRD4WQK","hXpcOcBcNa","EdFcQW","AwdcPvOv","k1L4wmoktSohWOH2rq","W4nxACo8xmkoWOhcHSkEWPFcQSouDZlcKmoaW74ky0RdPSoM","WPRdGfFcLCo+W4/dJ8kuWOO","WPeTaSoUW5/dIaa","WQDOW6C","WQldT8kezchcUqhcJ8kqrmoLW6WXyCosWRWiWPXgW6VdM8oWW69faCk1WQO","WPRcPumqWQKRxtS","W6qNh1vc","WQlcKmodDZpcUmo7wqFcOa","W7zVrWzt","W5hdUCoajq","ECoHqSkFqW","uttcVCkE","WRGXbmoUW4VdRYWdWOG","hL3dUvmoACkHWQq","WQFcI3KsWQ8LvYfKWQ8","g8orESk9W4e","W4jVla","W49wuMW","vCkYWQZdKfBdIWqIW44","tSkoWPq","WQbPW7tdRXz1tG","W6zkumklnmoX","FSk/W4WHaG","W5qEaCoq","WRD6v8kmW5RcPmkdW7WjW6pdRCksASkhW7pdMa","x8k6dbLvrXPtE8kbW7r6tSkfia","BSo6W77cLq","WRLqCa","WQqNaSoUW5ZdIq","sSoPnW","x1ZcKJ99W7n/","W6RdGIRcQr8","WOpdHNBcN8oDW5pdJCkYWPH9W4a","rmk7WQhdM1y","W4vormkhl8oRwCosFmoAW5S","eWaxWOi","FSoJt8kig8kaWPDmDrXFx10","W5VcR8kkBa","bCoaBSkaW5PaW4BdU8kAfmkVcx7dOa","sSo4rmknamksWQeaqbLvx0W","ptPV","WRhcNSoDEsZcJW","Eh/cP00","lXRdIa","AsxdTG","yNPq","WQddJ8kv","W6HBC8omsa","WQ/cTvWgWRGSrIbu","W5ldKSojiSkkDKpdSSorEG","WOKFW6tcRG7cUCkXW7VcQZtdKKVdMmoCWPBdGHjJWO46WQlcUSkSWOJdQ8oOWQi","W6WSp17cUmoWW4hcHfW","lX3dIa","W4ZcHgBcQwm","WRz8sG","ACkgpqLjvXfusG","d1ddTw7cGa","WPCcW4HO","WRz1qmkX","W4aefJizjbhdP1aTAspdIqpdSmkXW7JcGajCegWKAG","WQRcHrq","x8omW4hcMWVcRcTCW40","BmkGWQRcHbCvWQNcJ8oKWR8AzCkTW4VdNq","W7iVb1LeoIJcSq","CYClW515W4OxqWy","WPnTW5iEW6W","WRFdUSkaCtBcOWxcHG","W7zHqayh","W49xu2W","qvSyEmk9WQ/cNa","WQVcQSkpWRtdOcr9sW","W5PEqSkpnmoqFSo2xW","dGGiWOtdMSkwoCohgr8","FmoKqf1CWPS","W6a+f0HE","W7ddNclcPrpdSeS","W7i1pvtcH8oW","WRpcSmoglIe","W5uQj1JcHmomW4FcHeeO","zgSZs2u","W5RdKdddT3tdJmo3WODT","Adz6pIFcQSkUmJldQrRcV8onmW","WPNdHK0","WOFcMaRcTIG","CSkMlcm","WRVdRmkqCtZcGGi","W6RdSSowW6hcPa","WQddHSkvFq","WRP3W7ZdOXO","W5VcSXZdRW","yJX0mJRcRCk/ot7dVa","WQ/cQX/cKq","w1yoEmkGWO4","W58ubYqf","W745f1LogY8","W5lcTahdSCo/WRG4W6G","W7ldLCo9p8kgFG","tSk3BG","WRpcS8oo","W5pcRHhdPmo0W41X","WPCpW4C3","ySkUWRdcKXO2WRJcR8oIWR0","W5FdVConnCkv","W5VdKSoMpG","leHMxSodsG","rCkYWRRdPexdKbmQW5NcG8oXW5e","WOxdJeRcNmolW5xdMG","WRFdUSkrDW","WQiVW4dcPbNcR8kGW7C","AIeoW5z1W6OC","ceFdPW","p8oXWPxdPGq","WRHRtSkJ","WP3dQb5jWRG","A8oKWQDVfqhdUtO","cw9Eja","WRhcMSoDDsJcJ8oTqbZcPLS","Bmo7WPHYeW","AIpdLqiZ","oKxcVSkLW5WDW7eHgSo0W6y","gSo/WOS","WP3dPbHjWRG","W4vkqSkckmo5r8oE","WR9VrSkH","aLPjW50","W5VcQCkiBmky","zgSWsW","qSk3ACorW7NcOmob","vWtdHwbG","WQuJW6hcRGNcSW","CSkrW43dG8o2WOhdSCkmW7tcM2JcOXC2BmoWgmkdiK4pWRRdSGBdGSkltqC9j8k6WQxdV8oosqxcR0ZcRNS","WQuWW7/cOHG","W5tdK8oS","WPBcNaa","c0VdPvuFBG","WRdcHs/cLGZcHe5ulmouEa","wSoGvq","W4OodXCjnHVdPfu8CMpdJZxdTSoWW6lcLGvffsC8","DZXWhttcOmkU","WQBcMSoBxs3cMCoZtb3cVgPicCo/","WPvyWQK9iGOuhmouhGJcI8ottW","j0tcLSkVW5m3W6u","W7xdLYJcPX/dLW","W7RcVCoosJJdTKtdGW","CCoKWOm","mMyI","AGFdR0G","WOldH17cLComW5/dKCkuWP0","W5xdJ8o4nCkjretdGSow","gJH5WOqdASocWR/dR3avBtxdQSkRW7tdQ202dCoKWOzjW5y","W4xdKSodp8kCFLtdTCozF8oV","W4ZcHgtcQq","WO7cV1GDWRK","q8k4FSoYW67cJmosW6a","BmoGWO0","FSkYW4qHaG","htCdE8oyC8klWPqx","WQr3rSkH","W7iMif7cICoN","W4jQjSkrW6a","WO/cOeeAWQK","WQBcMSoBwtxcImoSqbhcVvXu","W4uZECoeW7C","WQuHamoNW5JdHb0","AatdTci","WRRdO8khwZpcOZtcMmknA8oLW6GKDa","W5dcJCk1","rgdcJv0K","grZcPqO","B8k+WQ3dHKVdKr0HW4G","jLLIxCo9r8osWO9Trmkf","WPqSWOLn","W6aZm1lcGmoEW5JcHvS0","W5VdQmoyomkv","tSklWPq","W6ldV8ohW6tcTwu5fCoqgX8Rl8o/hNW","gmoazmk1W5Hg","WPBcLSobFc7cI8oTcspcOeDFjq","rh7dTW","iK/cNmkTW58q","W7K4ba","w8orW73cMXBcStXl","W4RdKYVcSX7dKuRdR1ZcVWxdRCoWeCob","rJ/dNbuaWOm","WPL6W5eqW7yX","tSkiWPtcIG","W5pdSSoDm8kfxCkL","cIyV","WQPaW4GsW6a9y8kfw2pcG3KCWRNdR3/dVH4qW4SdmSkR","q8oHW7/cJKe","AstdVbi","eaOoWOldL8k1","W7JcRCkhWR0","W6jMt8kiW4xcSmk9","CCkZhqaz","z8k7WQNcNa","W4KefHmqjXNdRfO8wxxdQbi","WObXW5SsW6qWF8kjsq","WP3dOH5jW6W","wSkJdGvuDr1dsSkf","D2ddQSkB","sxJcQfOBrCkz","WQvOW7C","rhJdTW","d8oeyG","FZBcUmoeW71/ca","Bmk8aqHxvqC","W4VdQCoCjmke","W73dTCoCW7lcVxaJca","yNLDWOK","WPVcTvKLWRiRutbk","pZaj","W49rwa","W5eWy8ofW6e","W7BdHZlcPrNdT3NcGLi","qmofCG","CcOlW4fUW40","rgpcI10K","WRz+t8k8W5a","baWtWOVdNCk4pCoxgreC","sSoSnmko","s8kuW4VdGCoSWPZdSCkp","WRFcHrhcJq","s8k3W4BdJmoNWOBdT8kxWRNcT0tcKXShsSoWcCkAmuzcW6e","WRhdSmkrDtdcQchcHSkhDSoLW7qK","fCkMW4RcSW","W5qEda","W5ZdQCoxnCkjE8kSc8ovFmkGWPRcTab1zbjJcmoAW6Cczmo+B1BdTmohwmkjWQukhJldQ2LVsaO","W4uejmkdvq","W5rjvCkoi8o+tCotESoEW4pcJSkeWRxcVdOJW6BcRKRcLCk+arTZya","WQfQrSk9W4W","WQJcGW3cJam","aLfjW50","W4BcNqZdGmkCWOxcJmkEWO5xW5rTWP8","W7NcQaFdRSoHW6C","cK3dP1WBy8kR","rhZdUSob","WQePW70","i8oaF8k7W4y","W5dcJmk+ASko","pqFcQcFcKaZdSf/dPmoRW4n3rM1T","lt0aEW","W57dRSoqimkyya","WRRdO8kgCdpcRbBcJ8kHDmoUW7KLF8ovWRGsWPzq","sSk2WR3dU1pdJci1W5pcH8oXW5hcJCkz","eCoOWOJdRauAW7BcUq","W4vErCkc","t8k2BSobW6ZcISojW6C","WQ/cPbRcKq","W57dHt7dUNi","CYybW5y","W5/dMIFdVwi","gWJcOthcGWVdUrRdGG","tSklWPFdLqe","AspdUHir","zsmfW5X/","rvFcMd4","W6qYhvG","Cd8gW5P5","FCkiWQRdHK3dLbC1W6pcGSo6W5tcI8kbWQO6WQ52","W7e+bc4ymb3dV1e6rhNdJWhdQ8o/W6BcLa9n","wSoIxfy","bSooyq","W6GRnL7cLmogW5C","cfJcNCkNWOSFW6ywoCoMW6bamSkvW68OW4hdN1ZcSSo3W6O2W78","DZHUftRcRG","mMiUW5K","WOfWW6WdW7aWF8kl","ymklW7ddLmoWWOhdSmkf","W5rBDSoC","BdOEW5z/W60UzdK","WOJcV2eCWQONqbzyWOfd","WQG1WQdcSaS","WQddI8kBiG","W5qybSoq","W6b0zae","zSo+sCkjbG","WQ/cRb3cKq","vvLjW5pcGSoPBmolaGWDW5iE","y8oIxf9nWP0","W7JcG3BdUG","WPqVWOu","iL16DmobsSoEWOr3x8kBvCo/W6ZdG8oxWO1eW7zm","WOtdMeJcHa","h03dO3uwzCkJWQ8QWR5KvSoYga","FSk8W4yHaG","BN/cUHjXW4HPWO3dNX/cSvHhWRu","W5dcJmk3ASko","WPRdIe7cK8ocW5pdJa","W5qDaSoqiW","W7JcG3ZcPq","W63dTCoxmSkszCkWrCkLz8kQWOdcHq","cwfD","ceNdSW","wSoLvq","wSoNwvzD","W5VcQ8kaBmky","W6RdHJtcQqxdMetcQwC","W40oes8r"]');

# - Drop the shuffling function
lines = lines[0:60] + lines[871:]

# - Drop the fn_getStrings function
lines = lines[0:856] + lines[20339:]

with open(folder + "/logic.clean.02.js", "w") as f:
    f.write(lines)

# Deobfuscation #2.3: Removing decode

# - rename all clones of fn_decode
re_decode_aliases = re.compile('var\s+(_[0-9a-z]+_)\s*=\s*fn_decode\s*([;|,])')

match = re_decode_aliases.search(lines)
while match:
    identifier = match.group(1)
    terminator = match.group(2)
    # Replace fn alias
    if terminator == ";":
        lines = lines[0:match.start()] + lines[match.end():]
    else:
        lines = lines[0:match.start()] + "var " + lines[match.end():]
    # Replace fn calls
    lines = lines.replace(identifier, "fn_decode")
    # Find next match
    match = re_decode_aliases.search(lines)

# - lift the 277 subtraction
lines = lines.replace("_4573e4_ = _4573e4_ - 277;", "", 1)

re_decode_function = re.compile("fn_decode\(\s*(\d+)\s*,\s*('.*?')\s*\)")
def sub_decode_function(m):
    idx = int(m.group(1)) -277
    arg2 = m.group(2)
    return "fn_decode(" + str(idx) + ", " + arg2 + ")"
lines = re_decode_function.sub(sub_decode_function, lines)

# - rename arguments to help understanding (to no avail)
lines = lines.replace("_568a0e_", "_strings_") \
             .replace("_4573e4_", "_arg1_") \
             .replace("_131630_", "_arg2_") \
             .replace("_5307d8_", "_sub_and_decode_") \
             .replace("_2805dd_", "_inner_decode_") \
             .replace("_43e720_", "_memoize_key_") \
             .replace("_54c85d_", "_memoize_key_string_") \
             .replace("_522ffa_", "_memoize_value_") \
             .replace("_1bcbc1_", "_string_") \
             .replace("_243412_", "_arg_string_") \
             .replace("_407086_", "_arg_postfix_") \
             .replace("_380f42_", "i") \
             .replace("_4bb4a1_", "idx")

with open(folder + "/logic.clean.03.js", "w") as f:
    f.write(lines)

# Deobfuscation #2.4: Removing decode (using brute force)

# - write a JS to dump all decoded values to an object
re_decode_function = re.compile("fn_decode\(\s*(\d+)\s*,\s*('.*?')\s*\)")
with open(folder + "/logic.clean.03.eval.js", "w") as f:
    first = True
    f.write("{")
    for match in re_decode_function.finditer(lines):
        if not first:
            f.write(",")
        first = False
        f.write('"')
        f.write(match.group(0))
        f.write('": ')
        f.write(match.group(0))
    f.write("}")

# - manually run that JS in the browser to dump map of all strings
strings = {
    "fn_decode(259, 'mv54')": "replace",
    "fn_decode(593, 'JsDw')": "replace",
    "fn_decode(195, 'qdQl')": "[\\?&]",
    "fn_decode(594, '6pAS')": "=([^&#]*)",
    "fn_decode(823, 'B6$7')": "exec",
    "fn_decode(154, 'mw*O')": "search",
    "fn_decode(440, 'z!Em')": "replace",
    "fn_decode(500, '3NL2')": "cookie",
    "fn_decode(39, 'B6$7')": "match",
    "fn_decode(859, 'B6$7')": "(?:^|; )",
    "fn_decode(478, 'TGnN')": "replace",
    "fn_decode(246, 'h^JH')": "\\$1",
    "fn_decode(167, '6pAS')": "=([^;]*)",
    "fn_decode(63, 'mw*O')": "function",
    "fn_decode(721, '%&Rk')": "function",
    "fn_decode(17, 'ql@g')": "log",
    "fn_decode(980, 'h^JH')": "From getBackendParams():",
    "fn_decode(918, '3NL2')": "log",
    "fn_decode(567, 'mw*O')": "From cookies: ",
    "fn_decode(470, 'aX%g')": "length",
    "fn_decode(945, 'PGS(')": "abcdefghijklmnopqrstuvwxyz",
    "fn_decode(962, 'PGS(')": "push",
    "fn_decode(899, 'JsDw')": "charAt",
    "fn_decode(749, 'sf*h')": "floor",
    "fn_decode(393, 'yPd@')": "random",
    "fn_decode(674, 'lqJX')": "length",
    "fn_decode(819, 'xHch')": "join",
    "fn_decode(426, '9y9l')": "floor",
    "fn_decode(506, ')NM8')": "random",
    "fn_decode(789, 'HFXc')": "length",
    "fn_decode(414, 'I$aJ')": "replace",
    "fn_decode(811, 'mv54')": "https://",
    "fn_decode(157, 'CIJz')": "replace",
    "fn_decode(41, 'B6$7')": "http://",
    "fn_decode(637, 'L4pC')": "https://",
    "fn_decode(370, ')NM8')": "onload",
    "fn_decode(648, 'NFr5')": "userAgent",
    "fn_decode(866, 'xHch')": "toLowerCase",
    "fn_decode(462, ')NM8')": "indexOf",
    "fn_decode(152, '2ctN')": "windows phone",
    "fn_decode(90, '83VJ')": "Windows Phone",
    "fn_decode(141, 'sf*h')": "indexOf",
    "fn_decode(408, 'FIbR')": "win",
    "fn_decode(527, 'TMn5')": "Windows",
    "fn_decode(791, 'ZQpD')": "indexOf",
    "fn_decode(681, 'gZk6')": "kaios",
    "fn_decode(542, '$%Lg')": "Kaios",
    "fn_decode(394, '%&Rk')": "indexOf",
    "fn_decode(374, '3NL2')": "android",
    "fn_decode(746, 'yPd@')": "indexOf",
    "fn_decode(672, 'PGS(')": "spreadtrum",
    "fn_decode(284, 'HFXc')": "Android",
    "fn_decode(947, 'TMn5')": "linux",
    "fn_decode(158, '$%Lg')": "indexOf",
    "fn_decode(24, 'L4pC')": "cros",
    "fn_decode(306, 'JsDw')": "Linux",
    "fn_decode(736, '3NL2')": "indexOf",
    "fn_decode(164, 'FIbR')": "iphone",
    "fn_decode(625, 'mN)g')": "indexOf",
    "fn_decode(654, 'h3xB')": "ipad",
    "fn_decode(611, 'wIz[')": "iOS",
    "fn_decode(825, 'FIbR')": "indexOf",
    "fn_decode(101, 'HFXc')": "mac",
    "fn_decode(61, 'TGnN')": "Mac",
    "fn_decode(992, 'n1n*')": "Other",
    "fn_decode(230, 'wIz[')": "userAgent",
    "fn_decode(78, 'L4pC')": "indexOf",
    "fn_decode(862, 'JsDw')": "OPR/",
    "fn_decode(419, '83VJ')": "indexOf",
    "fn_decode(113, 'nyXr')": "Opera",
    "fn_decode(666, 'NFr5')": "Opera",
    "fn_decode(810, '6pAS')": "indexOf",
    "fn_decode(880, 'JsDw')": "MSIE",
    "fn_decode(75, 'PGS(')": "indexOf",
    "fn_decode(507, 'W3^v')": "Trident",
    "fn_decode(252, 'dQxJ')": "MAXTHON",
    "fn_decode(586, 'q3Na')": "Internet Explorer",
    "fn_decode(321, 'nyXr')": "Edge",
    "fn_decode(300, 'ql@g')": "EdgA",
    "fn_decode(957, ')jjB')": "Edge",
    "fn_decode(857, 'h^JH')": "indexOf",
    "fn_decode(260, '$%Lg')": "SamsungBrowser",
    "fn_decode(898, 'ZQpD')": "Samsung Browser",
    "fn_decode(56, 'I$aJ')": "indexOf",
    "fn_decode(395, 'FIbR')": "UCBrowser",
    "fn_decode(196, 'ql@g')": "UC Browser",
    "fn_decode(630, '9y9l')": "Android",
    "fn_decode(785, 'z!Em')": "indexOf",
    "fn_decode(174, '6pAS')": "Chrome",
    "fn_decode(631, 'TMn5')": "Firefox",
    "fn_decode(573, 'L4pC')": "Android Browser",
    "fn_decode(588, 'qdQl')": "Chrome",
    "fn_decode(799, 'TMn5')": "CriOS",
    "fn_decode(176, 'sf*h')": "Chrome",
    "fn_decode(219, 'CIJz')": "indexOf",
    "fn_decode(180, 'Q@&(')": "Safari",
    "fn_decode(639, 'NFr5')": "indexOf",
    "fn_decode(737, 'PGS(')": "Safari",
    "fn_decode(55, 'gZk6')": "indexOf",
    "fn_decode(536, 'q3Na')": "Firefox",
    "fn_decode(615, 'mN)g')": "Firefox",
    "fn_decode(320, 'HFXc')": "Other",
    "fn_decode(940, 'B6$7')": "createElement",
    "fn_decode(229, 'd4nD')": "canvas",
    "fn_decode(806, 'QFej')": "getContext",
    "fn_decode(85, 'n1n*')": "webgl",
    "fn_decode(280, 'B6$7')": "getExtension",
    "fn_decode(522, 'gZk6')": "WEBGL_debug_renderer_info",
    "fn_decode(445, 'ZQpD')": "getParameter",
    "fn_decode(469, 'HFXc')": "UNMASKED_VENDOR_WEBGL",
    "fn_decode(821, 'sf*h')": "getParameter",
    "fn_decode(302, 'Q@&(')": "UNMASKED_RENDERER_WEBGL",
    "fn_decode(926, '%&Rk')": "getVoices",
    "fn_decode(895, 'h^JH')": "length",
    "fn_decode(495, 'xHch')": "length",
    "fn_decode(415, '$%Lg')": "name",
    "fn_decode(463, '6pAS')": "languages",
    "fn_decode(248, '83VJ')": "undefined",
    "fn_decode(261, 'FIbR')": "languages",
    "fn_decode(168, 'mN)g')": "substr",
    "fn_decode(670, 'L4pC')": "language",
    "fn_decode(476, 'NFr5')": "substr",
    "fn_decode(814, 'B6$7')": "a1:",
    "fn_decode(1006, 'ZQpD')": "a1:e",
    "fn_decode(662, 'ZQpD')": "a1:",
    "fn_decode(166, '6pAS')": "screen",
    "fn_decode(201, '3NL2')": "width",
    "fn_decode(538, '9y9l')": "screen",
    "fn_decode(93, 'L4pC')": "availWidth",
    "fn_decode(850, 'd4nD')": "screen",
    "fn_decode(396, 'ql@g')": "height",
    "fn_decode(51, '83VJ')": "availHeight",
    "fn_decode(49, 'I$aJ')": "screen",
    "fn_decode(684, 'W3^v')": "width",
    "fn_decode(234, 't4!Z')": "screen",
    "fn_decode(308, '2ctN')": "availHeight",
    "fn_decode(808, 'z!Em')": "screen",
    "fn_decode(281, '9y9l')": "height",
    "fn_decode(45, 'FIbR')": "screen",
    "fn_decode(888, 'wIz[')": "availWidth",
    "fn_decode(907, 'qdQl')": "screen",
    "fn_decode(744, '83VJ')": "screen",
    "fn_decode(19, '$%Lg')": "availHeight",
    "fn_decode(485, '$%Lg')": "screen",
    "fn_decode(349, ')NM8')": "height",
    "fn_decode(489, 'q3Na')": "screen",
    "fn_decode(122, 'sf*h')": "availWidth",
    "fn_decode(587, 'z!Em')": "a2:",
    "fn_decode(304, 'DEe#')": "a2:",
    "fn_decode(125, 'mN)g')": "a2:",
    "fn_decode(624, 'CIJz')": "a2:e",
    "fn_decode(539, 'JsDw')": "oscpu",
    "fn_decode(872, ')jjB')": "undefined",
    "fn_decode(851, 'TMn5')": "toLowerCase",
    "fn_decode(28, 'h^JH')": "Kaios",
    "fn_decode(589, '9y9l')": "a3:",
    "fn_decode(697, 'HFXc')": "win",
    "fn_decode(305, 'ZQpD')": "Windows",
    "fn_decode(893, 'Q@&(')": "Windows Phone",
    "fn_decode(894, 'h3xB')": "a3:",
    "fn_decode(801, 'B6$7')": "indexOf",
    "fn_decode(266, 'W3^v')": "linux",
    "fn_decode(763, '6VU^')": "Linux",
    "fn_decode(917, '*lCG')": "Android",
    "fn_decode(591, 'QFej')": "a3:",
    "fn_decode(119, 'qdQl')": "mac",
    "fn_decode(509, ')NM8')": "Mac",
    "fn_decode(293, 'W3^v')": "iOS",
    "fn_decode(109, 'NFr5')": "a3:",
    "fn_decode(335, '3NL2')": "win",
    "fn_decode(417, 'n1n*')": "linux",
    "fn_decode(146, '9y9l')": "mac",
    "fn_decode(326, '2ctN')": "Other",
    "fn_decode(237, '2ctN')": "a3:",
    "fn_decode(861, ')NM8')": "a3:",
    "fn_decode(760, '*lCG')": "a3:",
    "fn_decode(318, 'sf*h')": "a3:e",
    "fn_decode(493, 'h^JH')": "oscpu",
    "fn_decode(968, 'I$aJ')": "undefined",
    "fn_decode(691, ')NM8')": "Firefox",
    "fn_decode(273, 'LB3Z')": "a4:",
    "fn_decode(89, 'nyXr')": "a4:",
    "fn_decode(635, '$%Lg')": "a4:e",
    "fn_decode(71, 'DW3R')": "platform",
    "fn_decode(344, 'nyXr')": "toLowerCase",
    "fn_decode(359, '%&Rk')": "userAgent",
    "fn_decode(84, '9y9l')": "toLowerCase",
    "fn_decode(827, 'CIJz')": "Kaios",
    "fn_decode(852, 'lqJX')": "a5:",
    "fn_decode(384, '6VU^')": "maui",
    "fn_decode(123, 'qdQl')": "indexOf",
    "fn_decode(966, 'FIbR')": "pike",
    "fn_decode(919, 'h3xB')": "a5:",
    "fn_decode(46, 'TGnN')": "indexOf",
    "fn_decode(612, 'yPd@')": "j2me/midp",
    "fn_decode(369, ')jjB')": "indexOf",
    "fn_decode(751, 'qdQl')": "pike",
    "fn_decode(890, '9y9l')": "a5:",
    "fn_decode(339, 'FIbR')": "arm",
    "fn_decode(1007, 't4!Z')": "Windows Phone",
    "fn_decode(325, 'I$aJ')": "a5:",
    "fn_decode(953, 'dQxJ')": "win",
    "fn_decode(162, 'PGS(')": "Windows",
    "fn_decode(752, 'n1n*')": "Windows Phone",
    "fn_decode(942, 'PGS(')": "a5:",
    "fn_decode(422, 'JsDw')": "indexOf",
    "fn_decode(187, 't4!Z')": "linux",
    "fn_decode(170, 'DW3R')": "android",
    "fn_decode(815, 'mv54')": "indexOf",
    "fn_decode(758, '*lCG')": "pike",
    "fn_decode(565, 'NFr5')": "Linux",
    "fn_decode(343, 'Q@&(')": "Android",
    "fn_decode(599, '83VJ')": "Kaios",
    "fn_decode(761, 'FIbR')": "a5:",
    "fn_decode(436, '2ctN')": "indexOf",
    "fn_decode(269, 'n1n*')": "mac",
    "fn_decode(843, 'DW3R')": "indexOf",
    "fn_decode(202, 'ql@g')": "ipad",
    "fn_decode(678, 'Q@&(')": "indexOf",
    "fn_decode(444, '83VJ')": "ipod",
    "fn_decode(566, 'nyXr')": "indexOf",
    "fn_decode(104, 'd4nD')": "iphone",
    "fn_decode(116, 'LB3Z')": "Mac",
    "fn_decode(57, '6pAS')": "iOS",
    "fn_decode(849, '$%Lg')": "a5:",
    "fn_decode(689, '3NL2')": "macintel",
    "fn_decode(820, 'L4pC')": "iphone",
    "fn_decode(655, 'h^JH')": "a5:",
    "fn_decode(143, 'TMn5')": "indexOf",
    "fn_decode(428, '$%Lg')": "win",
    "fn_decode(453, 'xHch')": "linux",
    "fn_decode(136, 'q3Na')": "indexOf",
    "fn_decode(546, ')NM8')": "mac",
    "fn_decode(985, '6VU^')": "pike",
    "fn_decode(680, 'TMn5')": "ipod",
    "fn_decode(515, 'd4nD')": "indexOf",
    "fn_decode(40, 'L4pC')": "ipad",
    "fn_decode(163, 'NFr5')": "Other",
    "fn_decode(617, 'ql@g')": "a5:",
    "fn_decode(742, 'gZk6')": "a5:e",
    "fn_decode(128, 'dQxJ')": "plugins",
    "fn_decode(528, 'TGnN')": "undefined",
    "fn_decode(922, 'lqJX')": "Windows",
    "fn_decode(199, '3NL2')": "Windows Phone",
    "fn_decode(194, 'gZk6')": "a6:",
    "fn_decode(442, '%&Rk')": "a6:",
    "fn_decode(901, '9y9l')": "a6:e",
    "fn_decode(97, 'yPd@')": "productSub",
    "fn_decode(950, 'mv54')": "Chrome",
    "fn_decode(345, 'CIJz')": "Safari",
    "fn_decode(786, 'W3^v')": "20030107",
    "fn_decode(455, 'TMn5')": "a7:",
    "fn_decode(623, 'ZQpD')": "Opera",
    "fn_decode(16, '$%Lg')": "20030107",
    "fn_decode(73, 'JsDw')": "undefined",
    "fn_decode(768, 'h^JH')": "a7:",
    "fn_decode(171, '*lCG')": "a7:",
    "fn_decode(22, 'FIbR')": "a7:e",
    "fn_decode(2, 't4!Z')": "toString",
    "fn_decode(578, 'NFr5')": "length",
    "fn_decode(277, 'DW3R')": "Safari",
    "fn_decode(197, 'h3xB')": "Firefox",
    "fn_decode(392, '*lCG')": "Other",
    "fn_decode(903, 'qdQl')": "iOS",
    "fn_decode(812, 'xHch')": "Chrome",
    "fn_decode(1008, ')jjB')": "a8:",
    "fn_decode(272, '6VU^')": "Internet Explorer",
    "fn_decode(834, 'JsDw')": "Other",
    "fn_decode(241, 'TMn5')": "a8:",
    "fn_decode(416, 'h3xB')": "Chrome",
    "fn_decode(220, 'yPd@')": "Opera",
    "fn_decode(642, 'mw*O')": "Edge",
    "fn_decode(239, 'q3Na')": "UC Browser",
    "fn_decode(956, 'I$aJ')": "Samsung Browser",
    "fn_decode(212, ')NM8')": "Other",
    "fn_decode(581, 'NFr5')": "Android Browser",
    "fn_decode(711, 'dQxJ')": "a8:",
    "fn_decode(770, '83VJ')": "a8:",
    "fn_decode(816, '2ctN')": "a8:e",
    "fn_decode(824, 'dQxJ')": "toSource",
    "fn_decode(399, '3NL2')": "Firefox",
    "fn_decode(482, 't4!Z')": "a9:",
    "fn_decode(548, 'HFXc')": "a9:",
    "fn_decode(803, 'Q@&(')": "a9:e",
    "fn_decode(139, 'z!Em')": "a10:",
    "fn_decode(743, 'mw*O')": "iOS",
    "fn_decode(511, 'DW3R')": "Apple",
    "fn_decode(604, '*lCG')": "indexOf",
    "fn_decode(865, ')NM8')": "Imagination Technologies",
    "fn_decode(251, 'xHch')": "Mac",
    "fn_decode(288, 'mw*O')": "indexOf",
    "fn_decode(646, 'aX%g')": "Intel",
    "fn_decode(14, 'h3xB')": "indexOf",
    "fn_decode(111, 'B6$7')": "ATI Technologies",
    "fn_decode(380, 'ZQpD')": "NVIDIA Corporation",
    "fn_decode(682, 'DEe#')": "indexOf",
    "fn_decode(189, '6pAS')": "Apple",
    "fn_decode(996, 'ZQpD')": "a10:",
    "fn_decode(460, 'ZQpD')": "Android",
    "fn_decode(60, 'dQxJ')": "indexOf",
    "fn_decode(703, 'DW3R')": "Google Inc",
    "fn_decode(550, 'z!Em')": "NVIDIA Corporation",
    "fn_decode(311, 'h^JH')": "a10:",
    "fn_decode(1, 'h^JH')": "Windows",
    "fn_decode(552, 'HFXc')": "Edge",
    "fn_decode(885, 'sf*h')": "Microsoft",
    "fn_decode(671, 'q3Na')": "a10:",
    "fn_decode(262, '9y9l')": "Chrome",
    "fn_decode(718, '83VJ')": "Firefox",
    "fn_decode(492, 'I$aJ')": "Google Inc",
    "fn_decode(498, 'W3^v')": "a10:",
    "fn_decode(357, ')jjB')": "VMware",
    "fn_decode(366, 'PGS(')": "a10:",
    "fn_decode(774, '83VJ')": "a10:",
    "fn_decode(313, 'q3Na')": "a10:e",
    "fn_decode(626, 'qdQl')": "webdriver",
    "fn_decode(190, '2ctN')": "webdriver",
    "fn_decode(204, 'NFr5')": "a11:",
    "fn_decode(708, 'B6$7')": "a11:",
    "fn_decode(955, 'xHch')": "a11:e",
    "fn_decode(686, 'TMn5')": "permissions",
    "fn_decode(576, 'B6$7')": "query",
    "fn_decode(532, 'DW3R')": "notifications",
    "fn_decode(873, 'mw*O')": "then",
    "fn_decode(600, 'sf*h')": "permission",
    "fn_decode(575, '83VJ')": "denied",
    "fn_decode(676, 'dQxJ')": "state",
    "fn_decode(667, 'mv54')": "prompt",
    "fn_decode(571, 't4!Z')": "a12:",
    "fn_decode(467, ')NM8')": "a12:",
    "fn_decode(545, 'HFXc')": "a12:e",
    "fn_decode(26, 'DW3R')": "navigator",
    "fn_decode(832, 'Q@&(')": "permissions",
    "fn_decode(54, '%&Rk')": "query",
    "fn_decode(103, 'QFej')": "toString",
    "fn_decode(66, 'Q@&(')": "replace",
    "fn_decode(188, 'FIbR')": "function query() { [native code] }",
    "fn_decode(472, 'W3^v')": "replace",
    "fn_decode(675, 'lqJX')": "a13:",
    "fn_decode(897, '9y9l')": "toString",
    "fn_decode(250, 'z!Em')": "toString",
    "fn_decode(319, '6VU^')": "function toString() { [native code] }",
    "fn_decode(553, 'ql@g')": "replace",
    "fn_decode(145, 'Q@&(')": "a13:",
    "fn_decode(946, 'mw*O')": "query",
    "fn_decode(830, 'ql@g')": "toString",
    "fn_decode(282, 'I$aJ')": "hasOwnProperty",
    "fn_decode(622, 'PGS(')": "[[Handler]]",
    "fn_decode(184, 'mv54')": "query",
    "fn_decode(29, 'h^JH')": "toString",
    "fn_decode(340, 'h^JH')": "hasOwnProperty",
    "fn_decode(609, 'DW3R')": "[[Target]]",
    "fn_decode(809, 'aX%g')": "query",
    "fn_decode(512, ')NM8')": "toString",
    "fn_decode(100, '6pAS')": "hasOwnProperty",
    "fn_decode(699, 'h^JH')": "[[IsRevoked]]",
    "fn_decode(329, '83VJ')": "a13:",
    "fn_decode(960, 'sf*h')": "hasOwnProperty",
    "fn_decode(429, '3NL2')": "query",
    "fn_decode(295, '9y9l')": "a13:",
    "fn_decode(620, 'mw*O')": "a13:",
    "fn_decode(534, 'TMn5')": "a13:e",
    "fn_decode(178, 'ZQpD')": "Chrome",
    "fn_decode(423, 'Q@&(')": "iOS",
    "fn_decode(606, '6VU^')": "toString",
    "fn_decode(792, 'wIz[')": "spooky",
    "fn_decode(25, 'lqJX')": "debug",
    "fn_decode(669, '9y9l')": "a14:",
    "fn_decode(361, 'B6$7')": "a14:",
    "fn_decode(439, 'h^JH')": "a14:",
    "fn_decode(769, 'TGnN')": "a14:e",
    "fn_decode(886, 'L4pC')": "callPhantom",
    "fn_decode(937, 'NFr5')": "_phantom",
    "fn_decode(278, 'LB3Z')": "phantom",
    "fn_decode(479, 'Q@&(')": "some",
    "fn_decode(243, 'LB3Z')": "a15:",
    "fn_decode(301, 'CIJz')": "a15:",
    "fn_decode(477, 'B6$7')": "a15:e",
    "fn_decode(449, 't4!Z')": "__webdriver_evaluate",
    "fn_decode(614, 'QFej')": "__selenium_evaluate",
    "fn_decode(766, 'dQxJ')": "__webdriver_script_function",
    "fn_decode(904, 'q3Na')": "__webdriver_script_func",
    "fn_decode(387, 'h3xB')": "__webdriver_script_fn",
    "fn_decode(182, 'gZk6')": "__fxdriver_evaluate",
    "fn_decode(975, 'sf*h')": "__driver_unwrapped",
    "fn_decode(68, 'B6$7')": "__webdriver_unwrapped",
    "fn_decode(526, 'aX%g')": "__driver_evaluate",
    "fn_decode(44, 'W3^v')": "__selenium_unwrapped",
    "fn_decode(976, 'aX%g')": "__fxdriver_unwrapped",
    "fn_decode(425, 'NFr5')": "webdriver",
    "fn_decode(503, 'mv54')": "_phantom",
    "fn_decode(48, 'FIbR')": "__nightmare",
    "fn_decode(341, 'h^JH')": "_selenium",
    "fn_decode(683, 'NFr5')": "callPhantom",
    "fn_decode(218, ')jjB')": "callSelenium",
    "fn_decode(939, 'NFr5')": "_Selenium_IDE_Recorder",
    "fn_decode(314, 'h3xB')": "__stopAllTimers",
    "fn_decode(140, 'QFej')": "a16:",
    "fn_decode(88, '$%Lg')": "document",
    "fn_decode(993, 'nyXr')": "a16:",
    "fn_decode(782, 'B6$7')": "external",
    "fn_decode(961, 'CIJz')": "external",
    "fn_decode(53, 'TMn5')": "toString",
    "fn_decode(779, '6pAS')": "external",
    "fn_decode(454, 'mN)g')": "toString",
    "fn_decode(764, '%&Rk')": "Sequentum",
    "fn_decode(487, 'FIbR')": "a16:",
    "fn_decode(67, 'd4nD')": "document",
    "fn_decode(317, '*lCG')": "documentElement",
    "fn_decode(120, 'QFej')": "getAttribute",
    "fn_decode(613, '3NL2')": "selenium",
    "fn_decode(867, 'TGnN')": "a16:",
    "fn_decode(299, 'mw*O')": "document",
    "fn_decode(572, 'aX%g')": "documentElement",
    "fn_decode(227, 'h3xB')": "getAttribute",
    "fn_decode(3, 'gZk6')": "webdriver",
    "fn_decode(238, '6pAS')": "a16:",
    "fn_decode(963, 'DW3R')": "document",
    "fn_decode(741, 'lqJX')": "documentElement",
    "fn_decode(877, 'Q@&(')": "getAttribute",
    "fn_decode(958, 't4!Z')": "driver",
    "fn_decode(132, '3NL2')": "a16:",
    "fn_decode(649, 'h3xB')": "a16:",
    "fn_decode(991, 'wIz[')": "a16:",
    "fn_decode(653, ')NM8')": "a16:e",
    "fn_decode(707, 'I$aJ')": "__phantomas",
    "fn_decode(709, 'qdQl')": "some",
    "fn_decode(388, 'B6$7')": "a17:",
    "fn_decode(952, 'h3xB')": "a17:",
    "fn_decode(249, 'QFej')": "a17:e",
    "fn_decode(924, 'W3^v')": "document",
    "fn_decode(82, 'CIJz')": "match",
    "fn_decode(148, 'FIbR')": "document",
    "fn_decode(400, 'I$aJ')": "cache_",
    "fn_decode(584, 'JsDw')": "a18:",
    "fn_decode(312, 'ZQpD')": "a18:",
    "fn_decode(1003, 'xHch')": "a18:e",
    "fn_decode(471, 'NFr5')": "Buffer",
    "fn_decode(540, 'mN)g')": "a19:",
    "fn_decode(668, 'qdQl')": "a19:",
    "fn_decode(457, 'dQxJ')": "a19:e",
    "fn_decode(264, 'dQxJ')": "domAutomation",
    "fn_decode(853, 'aX%g')": "domAutomationController",
    "fn_decode(906, '*lCG')": "a20:",
    "fn_decode(842, 'QFej')": "a20:",
    "fn_decode(988, '3NL2')": "a20:e",
    "fn_decode(951, 'd4nD')": "replace",
    "fn_decode(943, 't4!Z')": "function setTimeout() { [native code] }",
    "fn_decode(225, 'mw*O')": "replace",
    "fn_decode(407, 'FIbR')": "a21:",
    "fn_decode(32, 'h^JH')": "a21:",
    "fn_decode(181, 'HFXc')": "a21:e",
    "fn_decode(508, 'Q@&(')": "toString",
    "fn_decode(854, 'QFej')": "replace",
    "fn_decode(846, 'NFr5')": "function setInterval() { [native code] }",
    "fn_decode(602, 'JsDw')": "a22:",
    "fn_decode(110, 'yPd@')": "a22:",
    "fn_decode(793, 'B6$7')": "a22:e",
    "fn_decode(211, 'z!Em')": "getElementById",
    "fn_decode(27, 'Q@&(')": "frmin",
    "fn_decode(778, 'gZk6')": "contentDocument",
    "fn_decode(998, 'L4pC')": "getElementsByTagName",
    "fn_decode(828, 'mw*O')": "html",
    "fn_decode(390, 'gZk6')": "outerHTML",
    "fn_decode(183, 'xHch')": "indexOf",
    "fn_decode(502, ')jjB')": "kasperskylab_antibanner",
    "fn_decode(561, 'h^JH')": "a23:1",
    "fn_decode(557, '9y9l')": "indexOf",
    "fn_decode(775, 'aX%g')": "netdefender/hui/ndhui.js",
    "fn_decode(914, '%&Rk')": "a23:1",
    "fn_decode(590, 'JsDw')": "getElementById",
    "fn_decode(483, ')jjB')": "abs-top-frame",
    "fn_decode(242, 'd4nD')": "outerHTML",
    "fn_decode(332, ')NM8')": "/html/top.html",
    "fn_decode(787, 'PGS(')": "outerHTML",
    "fn_decode(290, ')NM8')": "chrome-extension://",
    "fn_decode(910, 'HFXc')": "a23:1",
    "fn_decode(855, 'Q@&(')": "getElementById",
    "fn_decode(765, 'xHch')": "coFrameDiv",
    "fn_decode(986, 'FIbR')": "outerHTML",
    "fn_decode(856, '2ctN')": "coToolbarFrame",
    "fn_decode(647, 'h^JH')": "/toolbar/placeholder.html",
    "fn_decode(165, '83VJ')": "chrome-extension://",
    "fn_decode(409, ')jjB')": "a23:1",
    "fn_decode(38, '9y9l')": "getElementsByClassName",
    "fn_decode(521, 't4!Z')": "drweb_btn",
    "fn_decode(629, 'CIJz')": "length",
    "fn_decode(126, 'TGnN')": "a23:1",
    "fn_decode(795, 'QFej')": "a23:0",
    "fn_decode(324, 'B6$7')": "a23:0",
    "fn_decode(106, 'ZQpD')": "a23:e",
    "fn_decode(276, 'nyXr')": "a24:",
    "fn_decode(665, '83VJ')": "a24:e",
    "fn_decode(186, 'mw*O')": "productSub",
    "fn_decode(191, '2ctN')": "undefined",
    "fn_decode(618, 't4!Z')": "a25:",
    "fn_decode(461, 'TGnN')": "a25:",
    "fn_decode(64, 'qdQl')": "a25:e",
    "fn_decode(504, 'HFXc')": "a26:",
    "fn_decode(1011, 'lqJX')": "a26:e",
    "fn_decode(700, 'I$aJ')": "a27:",
    "fn_decode(286, '83VJ')": "a27:e",
    "fn_decode(283, 'Q@&(')": "a28:",
    "fn_decode(677, '$%Lg')": "a28:e",
    "fn_decode(431, 'xHch')": "toSource",
    "fn_decode(569, 'mw*O')": "true",
    "fn_decode(934, 'mw*O')": "false",
    "fn_decode(505, 'sf*h')": "a29:",
    "fn_decode(424, 'PGS(')": "a29:e",
    "fn_decode(20, 'I$aJ')": "oscpu",
    "fn_decode(863, '$%Lg')": "undefined",
    "fn_decode(362, 'yPd@')": "a30:false",
    "fn_decode(990, 'PGS(')": "a30:",
    "fn_decode(421, ')NM8')": "oscpu",
    "fn_decode(644, 'gZk6')": "a30:e",
    "fn_decode(577, '6pAS')": "a31:",
    "fn_decode(661, 'z!Em')": "toLowerCase",
    "fn_decode(292, '$%Lg')": "a31:e",
    "fn_decode(466, 'QFej')": "a32:",
    "fn_decode(363, 'n1n*')": "screen",
    "fn_decode(790, '6pAS')": "width",
    "fn_decode(481, 'I$aJ')": "a32:e",
    "fn_decode(753, 't4!Z')": "a33:",
    "fn_decode(915, 'lqJX')": "availWidth",
    "fn_decode(297, 'QFej')": "a33:e",
    "fn_decode(52, ')jjB')": "a34:",
    "fn_decode(537, '2ctN')": "screen",
    "fn_decode(386, ')jjB')": "height",
    "fn_decode(105, 'lqJX')": "a34:e",
    "fn_decode(840, 'qdQl')": "a35:",
    "fn_decode(161, 'nyXr')": "screen",
    "fn_decode(358, 't4!Z')": "availHeight",
    "fn_decode(397, '$%Lg')": "a35:e",
    "fn_decode(138, 'lqJX')": "languages",
    "fn_decode(224, 'mw*O')": "undefined",
    "fn_decode(887, 'q3Na')": "a36:",
    "fn_decode(160, 'CIJz')": "languages",
    "fn_decode(465, 'TGnN')": "substr",
    "fn_decode(693, 'TMn5')": "a36:undefinedC",
    "fn_decode(254, 'nyXr')": "a36:undefinedT",
    "fn_decode(484, '83VJ')": "a36:e",
    "fn_decode(583, 'wIz[')": "a37:",
    "fn_decode(529, 'yPd@')": "language",
    "fn_decode(352, 'aX%g')": "substr",
    "fn_decode(402, '2ctN')": "a37:undefined",
    "fn_decode(118, 'dQxJ')": "a37:e",
    "fn_decode(203, 'CIJz')": "toString",
    "fn_decode(92, 'TMn5')": "length",
    "fn_decode(519, 'gZk6')": "a38:",
    "fn_decode(413, '*lCG')": "a38:e",
    "fn_decode(450, 'TMn5')": "stack",
    "fn_decode(657, 'aX%g')": "indexOf",
    "fn_decode(579, 'xHch')": "phantomjs",
    "fn_decode(108, 'h3xB')": "a39:",
    "fn_decode(365, 'FIbR')": "a39:",
    "fn_decode(368, 'FIbR')": "a39:e",
    "fn_decode(79, 'NFr5')": "a40:",
    "fn_decode(543, 'W3^v')": "userAgent",
    "fn_decode(245, 'NFr5')": "a40:e",
    "fn_decode(800, 'lqJX')": "IsCO",
    "fn_decode(771, 'lqJX')": "RSRequest",
    "fn_decode(72, '2ctN')": "XMLHttpRequest",
    "fn_decode(255, 'DW3R')": "prototype",
    "fn_decode(173, '6pAS')": "open",
    "fn_decode(114, 'qdQl')": "toString",
    "fn_decode(884, 'd4nD')": "a42:",
    "fn_decode(206, 'h3xB')": "a42:",
    "fn_decode(129, 'DEe#')": "a42:e",
    "fn_decode(112, 'q3Na')": "klI",
    "fn_decode(353, 'TMn5')": "sCOR",
    "fn_decode(263, 'h3xB')": "SRequest",
    "fn_decode(11, 'z!Em')": "XMLHttpRequest",
    "fn_decode(777, '9y9l')": "prototype",
    "fn_decode(972, 'yPd@')": "send",
    "fn_decode(124, ')NM8')": "a43:",
    "fn_decode(6, '83VJ')": "a43:",
    "fn_decode(135, 'W3^v')": "a43:e",
    "fn_decode(989, 'Q@&(')": "a44:",
    "fn_decode(1002, 'yPd@')": "XMLHttpRequest",
    "fn_decode(274, '$%Lg')": "prototype",
    "fn_decode(839, 'mw*O')": "open",
    "fn_decode(337, 'nyXr')": "toString",
    "fn_decode(822, '$%Lg')": "replace",
    "fn_decode(563, 'TMn5')": "a44:e",
    "fn_decode(354, 'W3^v')": "a45:",
    "fn_decode(434, 'wIz[')": "prototype",
    "fn_decode(973, '6pAS')": "send",
    "fn_decode(597, 'gZk6')": "toString",
    "fn_decode(475, '2ctN')": "replace",
    "fn_decode(837, '%&Rk')": "a45:e",
    "fn_decode(456, 'yPd@')": "a46:",
    "fn_decode(373, 'aX%g')": "navigator",
    "fn_decode(638, 'TGnN')": "permissions",
    "fn_decode(574, '9y9l')": "query",
    "fn_decode(984, 'NFr5')": "toString",
    "fn_decode(933, 'JsDw')": "a46:e",
    "fn_decode(179, 'dQxJ')": "a47:",
    "fn_decode(568, 'NFr5')": "navigator",
    "fn_decode(59, 'qdQl')": "permissions",
    "fn_decode(7, 'xHch')": "query",
    "fn_decode(474, ')jjB')": "toString",
    "fn_decode(406, 'mv54')": "toString",
    "fn_decode(608, 'ZQpD')": "replace",
    "fn_decode(5, 'mN)g')": "a47:e",
    "fn_decode(351, 'gZk6')": "a48:",
    "fn_decode(983, 'q3Na')": "toString",
    "fn_decode(879, '83VJ')": "replace",
    "fn_decode(738, 'ql@g')": "a48:e",
    "fn_decode(214, 'QFej')": "a49:",
    "fn_decode(309, 'JsDw')": "toString",
    "fn_decode(523, 'yPd@')": "a49:e",
    "fn_decode(291, 'yPd@')": "navigator",
    "fn_decode(750, 'PGS(')": "permissions",
    "fn_decode(86, 'z!Em')": "query",
    "fn_decode(47, 'PGS(')": "toString",
    "fn_decode(592, 'DW3R')": "hasOwnProperty",
    "fn_decode(610, 'HFXc')": "[[Handler]]",
    "fn_decode(712, 'I$aJ')": "query",
    "fn_decode(403, 'aX%g')": "toString",
    "fn_decode(881, 'B6$7')": "hasOwnProperty",
    "fn_decode(730, '%&Rk')": "[[Target]]",
    "fn_decode(556, 'lqJX')": "query",
    "fn_decode(570, 'yPd@')": "hasOwnProperty",
    "fn_decode(256, 'I$aJ')": "[[IsRevoked]]",
    "fn_decode(94, 'LB3Z')": "a50:true",
    "fn_decode(411, 'lqJX')": "a50:false",
    "fn_decode(875, 'mN)g')": "a50:e",
    "fn_decode(497, '$%Lg')": "navigator",
    "fn_decode(65, 'FIbR')": "hasOwnProperty",
    "fn_decode(923, 't4!Z')": "query",
    "fn_decode(192, 't4!Z')": "a51:",
    "fn_decode(841, 't4!Z')": "a51:e",
    "fn_decode(376, '$%Lg')": "getElementById",
    "fn_decode(690, 'DEe#')": "frmin",
    "fn_decode(443, 'JsDw')": "contentDocument",
    "fn_decode(601, 'NFr5')": "getElementsByTagName",
    "fn_decode(490, '6pAS')": "html",
    "fn_decode(216, 'ql@g')": "outerHTML",
    "fn_decode(558, '3NL2')": "substring",
    "fn_decode(147, 'mv54')": "a52:",
    "fn_decode(95, 'lqJX')": "a52:e",
    "fn_decode(334, '6pAS')": "getElementById",
    "fn_decode(525, 'mN)g')": "abs-top-frame",
    "fn_decode(513, 'lqJX')": "outerHTML",
    "fn_decode(580, 'NFr5')": "a53:",
    "fn_decode(659, '%&Rk')": "a53:e",
    "fn_decode(912, 'aX%g')": "getElementById",
    "fn_decode(702, 'q3Na')": "coFrameDiv",
    "fn_decode(930, 'ZQpD')": "outerHTML",
    "fn_decode(418, 't4!Z')": "a54:",
    "fn_decode(107, '9y9l')": "a54:e",
    "fn_decode(716, '6VU^')": "getElementsByClassName",
    "fn_decode(864, 'xHch')": "drweb_btn",
    "fn_decode(900, 'q3Na')": "length",
    "fn_decode(773, '2ctN')": "a55:",
    "fn_decode(598, 'yPd@')": "a55:e",
    "fn_decode(634, 'dQxJ')": "undefined",
    "fn_decode(210, 'q3Na')": "a56:false",
    "fn_decode(452, ')jjB')": "a56:true",
    "fn_decode(970, '*lCG')": "a56:e",
    "fn_decode(796, 'TGnN')": "webdriver",
    "fn_decode(739, 'PGS(')": "a57:",
    "fn_decode(664, '6VU^')": "a57:e",
    "fn_decode(215, 'LB3Z')": "webdriver",
    "fn_decode(734, 'sf*h')": "webdriver",
    "fn_decode(15, 'ql@g')": "a58:",
    "fn_decode(267, 'QFej')": "a58:e",
    "fn_decode(336, 'LB3Z')": "sper",
    "fn_decode(870, 'ql@g')": "sky",
    "fn_decode(247, ')jjB')": "klTabId",
    "fn_decode(177, '6VU^')": "endmicro",
    "fn_decode(172, 'I$aJ')": "pwm_scout",
    "fn_decode(99, ')jjB')": "vira",
    "fn_decode(1014, 'aX%g')": "cosym",
    "fn_decode(58, '%&Rk')": "antecnisbfw",
    "fn_decode(1000, 'd4nD')": "getElementById",
    "fn_decode(781, 'q3Na')": "frmin",
    "fn_decode(342, 'TGnN')": "getElementsByTagName",
    "fn_decode(911, 'gZk6')": "html",
    "fn_decode(728, '83VJ')": "outerHTML",
    "fn_decode(921, 'LB3Z')": "indexOf",
    "fn_decode(377, 'n1n*')": "a59:",
    "fn_decode(936, 'DW3R')": "a59:",
    "fn_decode(969, '9y9l')": "a59:e",
    "fn_decode(780, 'FIbR')": "phantomjs",
    "fn_decode(159, 'mN)g')": "headless",
    "fn_decode(714, '*lCG')": "avira",
    "fn_decode(987, '%&Rk')": "toLowerCase",
    "fn_decode(223, '%&Rk')": "a60:",
    "fn_decode(585, 'lqJX')": "a60:",
    "fn_decode(772, 'I$aJ')": "a60:e",
    "fn_decode(559, 'FIbR')": "getTimezoneOffset",
    "fn_decode(784, 'aX%g')": "a61:",
    "fn_decode(905, 'sf*h')": "a61:e",
    "fn_decode(514, 't4!Z')": "Intl",
    "fn_decode(378, 'aX%g')": "DateTimeFormat",
    "fn_decode(451, '6VU^')": "resolvedOptions",
    "fn_decode(296, 'CIJz')": "timeZone",
    "fn_decode(77, 'B6$7')": "a62:",
    "fn_decode(382, 'dQxJ')": "a62:e",
    "fn_decode(285, 'ql@g')": "PointerEvent",
    "fn_decode(30, '*lCG')": "maxTouchPoints",
    "fn_decode(754, 'DEe#')": "maxTouchPoints",
    "fn_decode(551, 'h3xB')": "a63:1",
    "fn_decode(37, 'I$aJ')": "a63:0",
    "fn_decode(232, '83VJ')": "msMaxTouchPoints",
    "fn_decode(464, 'q3Na')": "a63:1",
    "fn_decode(788, 'qdQl')": "matchMedia",
    "fn_decode(817, 'gZk6')": "matchMedia",
    "fn_decode(315, 'TGnN')": "(any-pointer:coarse)",
    "fn_decode(1004, '$%Lg')": "matches",
    "fn_decode(226, 'xHch')": "a63:1",
    "fn_decode(794, 'wIz[')": "TouchEvent",
    "fn_decode(222, 'xHch')": "ontouchstart",
    "fn_decode(783, '6pAS')": "a63:1",
    "fn_decode(518, 'NFr5')": "a63:0",
    "fn_decode(844, 'yPd@')": "a63:e",
    "fn_decode(12, 'wIz[')": "navigator",
    "fn_decode(391, 'I$aJ')": "buildID",
    "fn_decode(807, 'nyXr')": "a64:",
    "fn_decode(1005, 'PGS(')": "a64:e",
    "fn_decode(516, 'JsDw')": "navigation",
    "fn_decode(640, 'z!Em')": "redirectCount",
    "fn_decode(633, 'TMn5')": "a65:",
    "fn_decode(517, 'h^JH')": "a65:e",
    "fn_decode(715, 'L4pC')": "navigation",
    "fn_decode(142, 'Q@&(')": "type",
    "fn_decode(941, 'CIJz')": "a66:",
    "fn_decode(323, 'L4pC')": "a66:e",
    "fn_decode(137, 't4!Z')": "msOrientation",
    "fn_decode(797, 'QFej')": "mozOrientation",
    "fn_decode(350, 'LB3Z')": "orientation",
    "fn_decode(727, 'h3xB')": "type",
    "fn_decode(925, 'FIbR')": "a67:",
    "fn_decode(134, 'NFr5')": "a67:e",
    "fn_decode(193, 'z!Em')": "devicePixelRatio",
    "fn_decode(81, 'CIJz')": "a68:",
    "fn_decode(235, ')jjB')": "a68:e",
    "fn_decode(692, 'ql@g')": "screen",
    "fn_decode(74, 'aX%g')": "pixelDepth",
    "fn_decode(831, ')jjB')": "a69:",
    "fn_decode(944, '6VU^')": "a69:e",
    "fn_decode(995, 'HFXc')": "screen",
    "fn_decode(723, 'Q@&(')": "colorDepth",
    "fn_decode(733, 'aX%g')": "a70:",
    "fn_decode(883, 'JsDw')": "a70:e",
    "fn_decode(874, 'wIz[')": "screen",
    "fn_decode(656, 'I$aJ')": "deviceXDPI",
    "fn_decode(0, 'mw*O')": "a71:",
    "fn_decode(364, 'I$aJ')": "a71:e",
    "fn_decode(845, 'dQxJ')": "screen",
    "fn_decode(150, 'TGnN')": "deviceYDPI",
    "fn_decode(398, '%&Rk')": "a72:",
    "fn_decode(1001, 'ql@g')": "a72:e",
    "fn_decode(651, ')NM8')": "function",
    "fn_decode(869, 'DW3R')": "hasFocus",
    "fn_decode(18, 'TGnN')": "hasFocus",
    "fn_decode(977, 'lqJX')": "a73:",
    "fn_decode(185, 'B6$7')": "a73:e",
    "fn_decode(740, 'mw*O')": "getComputedStyle",
    "fn_decode(307, '9y9l')": "a74:",
    "fn_decode(270, 'PGS(')": "a74:e",
    "fn_decode(322, ')jjB')": "a75:",
    "fn_decode(348, 'h^JH')": "function",
    "fn_decode(695, 'mw*O')": "sendBeacon",
    "fn_decode(34, 'PGS(')": "a75:e",
    "fn_decode(982, ')NM8')": "a76:",
    "fn_decode(935, 'qdQl')": "geolocation",
    "fn_decode(289, 'lqJX')": "a76:e",
    "fn_decode(207, 't4!Z')": "Test Error",
    "fn_decode(385, 'lqJX')": "stack",
    "fn_decode(704, 'xHch')": "obj",
    "fn_decode(151, 'z!Em')": "propName",
    "fn_decode(338, '*lCG')": "apply",
    "fn_decode(438, 'TMn5')": "obj",
    "fn_decode(688, 'yPd@')": "propName",
    "fn_decode(10, 'ZQpD')": "querySelector",
    "fn_decode(155, '2ctN')": "querySelector",
    "fn_decode(720, 'B6$7')": "puppeteer_evaluation_script",
    "fn_decode(458, 'HFXc')": "a77:true",
    "fn_decode(209, 'JsDw')": "a77:false",
    "fn_decode(33, 'NFr5')": "a77:e",
    "fn_decode(755, 'n1n*')": "createElement",
    "fn_decode(496, 'B6$7')": "stack",
    "fn_decode(401, 'h^JH')": "split",
    "fn_decode(328, '$%Lg')": "length",
    "fn_decode(818, 't4!Z')": "match",
    "fn_decode(441, 'sf*h')": "a78:",
    "fn_decode(908, 'W3^v')": "a78:",
    "fn_decode(641, 'W3^v')": "getOwnPropertyDescriptor",
    "fn_decode(149, 'TMn5')": "getPrototypeOf",
    "fn_decode(367, 'aX%g')": "hardwareConcurrency",
    "fn_decode(236, 'wIz[')": "value",
    "fn_decode(221, '9y9l')": "value",
    "fn_decode(268, 'xHch')": "get",
    "fn_decode(198, 'nyXr')": "get",
    "fn_decode(175, 'DEe#')": "undefined",
    "fn_decode(696, 'I$aJ')": "a79:",
    "fn_decode(616, 'yPd@')": "replace",
    "fn_decode(1012, 't4!Z')": "a79:e",
    "fn_decode(798, '$%Lg')": "now",
    "fn_decode(756, ')NM8')": "now",
    "fn_decode(836, 'CIJz')": "now",
    "fn_decode(330, 'QFej')": "push",
    "fn_decode(971, 'FIbR')": "floor",
    "fn_decode(981, 'QFej')": "random",
    "fn_decode(826, 'd4nD')": "pop",
    "fn_decode(23, 'QFej')": "now",
    "fn_decode(719, '3NL2')": "now",
    "fn_decode(713, 'LB3Z')": "now",
    "fn_decode(549, 'xHch')": "setItem",
    "fn_decode(636, 'qdQl')": "constant string",
    "fn_decode(316, 'n1n*')": "removeItem",
    "fn_decode(379, 'mN)g')": "a83:",
    "fn_decode(967, 'TGnN')": "round",
    "fn_decode(829, '%&Rk')": "a83:e",
    "fn_decode(878, 'mN)g')": "floor",
    "fn_decode(619, 'JsDw')": "now",
    "fn_decode(896, '6pAS')": "now",
    "fn_decode(860, 'ql@g')": "now",
    "fn_decode(83, 'B6$7')": "a84:",
    "fn_decode(929, 'mN)g')": "round",
    "fn_decode(724, '6pAS')": "a84:e",
    "fn_decode(347, ')NM8')": "abs",
    "fn_decode(253, '9y9l')": "acos",
    "fn_decode(805, 'mv54')": "asin",
    "fn_decode(889, 't4!Z')": "atanh",
    "fn_decode(4, 't4!Z')": "cbrt",
    "fn_decode(520, '2ctN')": "exp",
    "fn_decode(494, 'JsDw')": "random",
    "fn_decode(868, '%&Rk')": "round",
    "fn_decode(999, '$%Lg')": "sqrt",
    "fn_decode(628, 'xHch')": "parse",
    "fn_decode(8, 'z!Em')": "length",
    "fn_decode(978, 'DEe#')": "now",
    "fn_decode(776, 'TMn5')": "now",
    "fn_decode(31, 'dQxJ')": "push",
    "fn_decode(595, 'xHch')": "round",
    "fn_decode(938, 'TMn5')": "sort",
    "fn_decode(524, 'TGnN')": "floor",
    "fn_decode(62, 'FIbR')": "length",
    "fn_decode(948, 'qdQl')": "a85:",
    "fn_decode(499, 'z!Em')": "a85:e",
    "fn_decode(42, 'nyXr')": "navigator",
    "fn_decode(310, '83VJ')": "hardwareConcurrency",
    "fn_decode(240, 'B6$7')": "navigator",
    "fn_decode(663, 'TMn5')": "hardwareConcurrency",
    "fn_decode(916, 'LB3Z')": "a86:",
    "fn_decode(679, 'FIbR')": "a86:",
    "fn_decode(228, 'Q@&(')": "a86:e",
    "fn_decode(835, 'h^JH')": "toLowerCase",
    "fn_decode(902, 't4!Z')": "indexOf",
    "fn_decode(275, '*lCG')": "lekha",
    "fn_decode(381, 'NFr5')": "a87:Mac",
    "fn_decode(244, '*lCG')": "toLowerCase",
    "fn_decode(35, 'DEe#')": "microsoft",
    "fn_decode(607, 'd4nD')": "a87:Windows",
    "fn_decode(459, 'mw*O')": "toLowerCase",
    "fn_decode(643, 'xHch')": "chrome os",
    "fn_decode(621, 'JsDw')": "a87:Chrome OS",
    "fn_decode(748, '$%Lg')": "toLowerCase",
    "fn_decode(13, 'mw*O')": "android",
    "fn_decode(69, 'ql@g')": "a87:Android",
    "fn_decode(372, 'DEe#')": "a87:undefined",
    "fn_decode(133, '$%Lg')": "a88:",
    "fn_decode(389, 'n1n*')": "navigator",
    "fn_decode(959, 'B6$7')": "hardwareConcurrency",
    "fn_decode(258, '2ctN')": "a88:e",
    "fn_decode(541, 'DEe#')": "toLowerCase",
    "fn_decode(70, '2ctN')": "lekha",
    "fn_decode(927, ')jjB')": "Win",
    "fn_decode(87, 'z!Em')": "Kaios",
    "fn_decode(91, 'CIJz')": "Android",
    "fn_decode(694, 'yPd@')": "Linux",
    "fn_decode(437, 'sf*h')": "a89:",
    "fn_decode(544, 'QFej')": "toLowerCase",
    "fn_decode(979, 'wIz[')": "indexOf",
    "fn_decode(121, ')jjB')": "microsoft",
    "fn_decode(954, 'DEe#')": "Kaios",
    "fn_decode(562, '2ctN')": "Linux",
    "fn_decode(931, 'n1n*')": "iOS",
    "fn_decode(360, '83VJ')": "Mac",
    "fn_decode(333, 'ZQpD')": "a89:",
    "fn_decode(448, 'PGS(')": "getOwnPropertyDescriptor",
    "fn_decode(554, 'B6$7')": "getPrototypeOf",
    "fn_decode(706, 'qdQl')": "hardwareConcurrency",
    "fn_decode(371, 'mw*O')": "value",
    "fn_decode(405, 'LB3Z')": "value",
    "fn_decode(920, 'DEe#')": "get",
    "fn_decode(127, '3NL2')": "get",
    "fn_decode(913, 'q3Na')": "undefined",
    "fn_decode(298, 'aX%g')": "undefined",
    "fn_decode(660, 'B6$7')": "replace",
    "fn_decode(652, 'h3xB')": "nativecode",
    "fn_decode(287, 'NFr5')": "a90:",
    "fn_decode(627, 'h3xB')": "a90:",
    "fn_decode(871, 'ql@g')": "a90:e",
    "fn_decode(767, 'wIz[')": "mimeTypes",
    "fn_decode(355, 'LB3Z')": "application/x-nacl",
    "fn_decode(717, '$%Lg')": "mimeTypes",
    "fn_decode(76, '2ctN')": "application/x-pnacl",
    "fn_decode(9, 'q3Na')": "a91:",
    "fn_decode(964, 'nyXr')": "a91:",
    "fn_decode(701, 'h3xB')": "a91:e",
    "fn_decode(560, 'sf*h')": "split",
    "fn_decode(547, 'gZk6')": "a0:",
    "fn_decode(847, 'dQxJ')": "split",
    "fn_decode(1010, 'lqJX')": "a0:",
    "fn_decode(430, 'PGS(')": "split",
    "fn_decode(650, '6pAS')": "a0:",
    "fn_decode(804, '3NL2')": "split",
    "fn_decode(130, '%&Rk')": "a0:",
    "fn_decode(331, 'B6$7')": "split",
    "fn_decode(50, 'q3Na')": "split",
    "fn_decode(117, 'ql@g')": "a0:",
    "fn_decode(747, 'ZQpD')": "split",
    "fn_decode(96, '$%Lg')": "a0:",
    "fn_decode(488, 'gZk6')": "split",
    "fn_decode(603, 'd4nD')": "a0:",
    "fn_decode(156, 'qdQl')": "split",
    "fn_decode(759, 'h^JH')": "a0:",
    "fn_decode(346, 'z!Em')": "split",
    "fn_decode(745, 'DW3R')": "a0:",
    "fn_decode(427, 'h3xB')": "split",
    "fn_decode(501, 'yPd@')": "a0:",
    "fn_decode(974, 'FIbR')": "split",
    "fn_decode(882, 'xHch')": "a0:",
    "fn_decode(722, '6pAS')": "split",
    "fn_decode(732, 'mN)g')": "a0:",
    "fn_decode(833, 'ql@g')": "split",
    "fn_decode(510, 'B6$7')": "a0:",
    "fn_decode(555, 'xHch')": "split",
    "fn_decode(762, 'Q@&(')": "a0:",
    "fn_decode(294, 'nyXr')": "split",
    "fn_decode(928, 'aX%g')": "a0:",
    "fn_decode(658, 'DW3R')": "split",
    "fn_decode(965, 'TGnN')": "split",
    "fn_decode(144, '2ctN')": "a0:",
    "fn_decode(102, 'mv54')": "split",
    "fn_decode(997, 'q3Na')": "a0:",
    "fn_decode(446, 'wIz[')": "split",
    "fn_decode(21, 'TMn5')": "a0:",
    "fn_decode(876, '%&Rk')": "split",
    "fn_decode(279, 'FIbR')": "a0:",
    "fn_decode(213, '6VU^')": "split",
    "fn_decode(735, '9y9l')": "a0:",
    "fn_decode(473, 'I$aJ')": "split",
    "fn_decode(731, 'DEe#')": "split",
    "fn_decode(412, 'L4pC')": "a0:",
    "fn_decode(233, ')jjB')": "split",
    "fn_decode(169, 'DEe#')": "a0:",
    "fn_decode(257, 'h3xB')": "a0:",
    "fn_decode(98, 'TMn5')": "a0:e",
    "fn_decode(729, 'd4nD')": "function",
    "fn_decode(491, '6VU^')": "length",
    "fn_decode(327, 'L4pC')": "split",
    "fn_decode(858, 'ZQpD')": "length",
    "fn_decode(802, 'W3^v')": "shift",
    "fn_decode(131, 'gZk6')": "join",
    "fn_decode(1013, 'ZQpD')": "stringify",
    "fn_decode(891, 'W3^v')": "{exception:true}",
    "fn_decode(356, 'I$aJ')": "location",
    "fn_decode(725, 't4!Z')": "keys",
    "fn_decode(757, 'Q@&(')": "params",
    "fn_decode(564, 'd4nD')": "forEach",
    "fn_decode(892, 'DEe#')": "params",
    "fn_decode(435, 'lqJX')": "jsFpCryptoKey",
    "fn_decode(848, 'xHch')": "enc",
    "fn_decode(645, 'W3^v')": "Utf8",
    "fn_decode(265, 'dQxJ')": "parse",
    "fn_decode(698, ')jjB')": "AES",
    "fn_decode(468, 'wIz[')": "encrypt",
    "fn_decode(813, 'DW3R')": "enc",
    "fn_decode(271, 't4!Z')": "Utf8",
    "fn_decode(530, 'gZk6')": "parse",
    "fn_decode(710, 'TMn5')": "mode",
    "fn_decode(115, 'DW3R')": "CBC",
    "fn_decode(1009, 'd4nD')": "pad",
    "fn_decode(726, 'n1n*')": "Pkcs7",
    "fn_decode(231, '*lCG')": "ntkn",
    "fn_decode(410, '*lCG')": "sid",
    "fn_decode(673, 'h3xB')": "sessionId",
    "fn_decode(486, 'ql@g')": "location",
    "fn_decode(432, '3NL2')": "replace",
    "fn_decode(383, 'FIbR')": "f=1&sid=",
    "fn_decode(303, 'DW3R')": "&fp=",
    "fn_decode(433, 'q3Na')": "location",
    "fn_decode(153, 'h^JH')": "f=1&fp=",
    "fn_decode(480, '2ctN')": "createElement",
    "fn_decode(205, 'W3^v')": "href",
    "fn_decode(447, 'sf*h')": "hostname",
    "fn_decode(632, ')NM8')": "origin",
    "fn_decode(838, 'PGS(')": "pathname",
    "fn_decode(932, 'FIbR')": "search",
    "fn_decode(80, 'Q@&(')": "length"
}

# - replace all map keys with their values
for key in strings.keys():
    lines = lines.replace(key, "'" + strings[key] + "'")

# - Drop the getUrlParameter function which is no longer in use
lines = lines[400:]

# - Drop the getBackendParamsByNameReverse function which is no longer in use
lines = lines[0:830] + lines[1277:]

# - Drop the fn_decode function which is no longer in use
lines = lines[0:1376] + lines[22618:]

# - Drop the rString function which is no longer in use
lines = lines[0:830] + lines[1055:]

with open(folder + "/logic.clean.04.js", "w") as f:
    f.write(lines)

# Deobfuscation #2.5: Simplify again

# - Array notation to dot notation
lines = transform_arraystyle_fn_calls(lines)

# - Rename other parts of the code after learning their behaviour
lines = lines.replace("_3f5296_", "checks") \
             .replace("_36eee5_", "idx") \
             .replace("_2da39b_", "check_outcome") \
             .replace("_56e002_", "all_check_outcomes") \
             .replace("_37323d_", "fingerprint")

with open(folder + "/logic.clean.05.js", "w") as f:
    f.write(lines)

with open(folder + "/logic.clean.js", "w") as f:
    f.write(lines)